import { describe, expect, it } from '@sqldoc/test-utils'
import type { SqlAstAdapter } from '../../ast/adapter.ts'
import type { SqlStatement } from '../../ast/types.ts'
import { compile } from '../../compiler/compile.ts'
import type { NamespacePlugin, ResolvedConfig } from '../../compiler/types.ts'

/** Stub adapter that returns no comments */
const stubAdapter: SqlAstAdapter = {
  async init() {},
  parseStatements() {
    return []
  },
  parseComments() {
    return []
  },
}

// -- Test helpers --

function makePlugin(overrides: Partial<NamespacePlugin> & { name: string }): NamespacePlugin {
  return {
    apiVersion: 1,
    tags: {},
    ...overrides,
  }
}

/** Helper to get 1-based line number of a substring in source */
function lineOf(source: string, search: string): number {
  const idx = source.indexOf(search)
  if (idx === -1) return 1
  return source.substring(0, idx).split('\n').length
}

function makeStatements(stmts: Partial<SqlStatement>[]): SqlStatement[] {
  return stmts.map((s, _i) => ({
    kind: s.kind ?? 'table',
    objectName: s.objectName ?? 'unknown',
    line: s.line ?? 1,
    columns: s.columns,
    raw: s.raw ?? null,
  }))
}

// -- Tests --

describe('compile()', () => {
  it('returns SqlOutput[] in CompilerOutput.sqlOutputs from generateSQL', () => {
    const plugin = makePlugin({
      name: 'test',
      tags: { label: { args: [{ type: 'string' }] } },
      generateSQL: (ctx) => [{ sql: `-- generated for ${ctx.objectName}` }],
    })

    const source = ["-- @test.label('users-table')", 'CREATE TABLE users (', '  id SERIAL PRIMARY KEY', ');'].join('\n')

    const result = compile({
      source,
      filePath: 'test.sql',
      plugins: new Map([['test', plugin]]),
      statements: makeStatements([{ kind: 'table', objectName: 'users', line: lineOf(source, 'CREATE') }]),
      adapter: stubAdapter,
      config: { dialect: 'postgres' },
    })

    expect(result.sqlOutputs).toHaveLength(1)
    expect(result.sqlOutputs[0].sql).toBe('-- generated for users')
    expect(result.sourceFile).toBe('test.sql')
    // mergedSql should contain original source + generated SQL
    expect(result.mergedSql).toContain('CREATE TABLE users')
    expect(result.mergedSql).toContain('-- generated for users')
    expect(result.mergedSql).toContain('-- Generated by sqldoc')
  })

  it('returns CodeOutput[] in CompilerOutput.codeOutputs from generateCode', () => {
    const plugin = makePlugin({
      name: 'codegen',
      tags: { types: {} },
      generateCode: (ctx) => [{ filePath: `${ctx.objectName}.ts`, content: `export type ${ctx.objectName} = {}` }],
    })

    const source = ['-- @codegen.types', 'CREATE TABLE orders (', '  id SERIAL', ');'].join('\n')

    const result = compile({
      source,
      filePath: 'orders.sql',
      plugins: new Map([['codegen', plugin]]),
      statements: makeStatements([{ kind: 'table', objectName: 'orders', line: lineOf(source, 'CREATE') }]),
      adapter: stubAdapter,
      config: { dialect: 'postgres' },
    })

    expect(result.codeOutputs).toHaveLength(1)
    expect(result.codeOutputs[0].filePath).toBe('orders.ts')
    expect(result.codeOutputs[0].content).toBe('export type orders = {}')
  })

  it('populates CompilerContext.siblingTags with tags from other namespaces on same object', () => {
    let capturedCtx: any = null

    const pluginA = makePlugin({
      name: 'alpha',
      tags: { run: {} },
      generateSQL: (ctx) => {
        capturedCtx = ctx
        return []
      },
    })

    const pluginB = makePlugin({
      name: 'beta',
      tags: { check: { args: [{ type: 'string' }] } },
    })

    const source = ['-- @alpha.run', "-- @beta.check('strict')", 'CREATE TABLE products (', '  id SERIAL', ');'].join(
      '\n',
    )

    compile({
      source,
      filePath: 'products.sql',
      plugins: new Map([
        ['alpha', pluginA],
        ['beta', pluginB],
      ]),
      statements: makeStatements([{ kind: 'table', objectName: 'products', line: lineOf(source, 'CREATE') }]),
      adapter: stubAdapter,
      config: { dialect: 'postgres' },
    })

    expect(capturedCtx).not.toBe(null)
    expect(capturedCtx.siblingTags.some((t: any) => t.namespace === 'beta' && t.tag === 'check')).toBeTruthy()
    // siblingTags should include tags from ALL namespaces (including own)
    expect(capturedCtx.siblingTags.some((t: any) => t.namespace === 'alpha' && t.tag === 'run')).toBeTruthy()
  })

  it('populates CompilerContext.fileTags with all tags across file grouped by object', () => {
    let capturedCtx: any = null

    const plugin = makePlugin({
      name: 'ns',
      tags: { a: {}, b: {} },
      generateSQL: (ctx) => {
        capturedCtx = ctx
        return []
      },
    })

    const source = [
      '-- @ns.a',
      'CREATE TABLE t1 (',
      '  id SERIAL',
      ');',
      '',
      '-- @ns.b',
      'CREATE TABLE t2 (',
      '  id SERIAL',
      ');',
    ].join('\n')

    compile({
      source,
      filePath: 'multi.sql',
      plugins: new Map([['ns', plugin]]),
      statements: makeStatements([
        { kind: 'table', objectName: 't1', line: lineOf(source, 'CREATE TABLE t1') },
        { kind: 'table', objectName: 't2', line: lineOf(source, 'CREATE TABLE t2') },
      ]),
      adapter: stubAdapter,
      config: { dialect: 'postgres' },
    })

    expect(capturedCtx).not.toBe(null)
    expect(capturedCtx.fileTags).toHaveLength(2)
    expect(capturedCtx.fileTags.some((ft: any) => ft.objectName === 't1')).toBeTruthy()
    expect(capturedCtx.fileTags.some((ft: any) => ft.objectName === 't2')).toBeTruthy()
  })

  it('populates CompilerContext.config with namespace-specific config from ProjectConfig', () => {
    let capturedCtx: any = null

    const plugin = makePlugin({
      name: 'myns',
      tags: { go: {} },
      generateSQL: (ctx) => {
        capturedCtx = ctx
        return []
      },
    })

    const source = ['-- @myns.go', 'CREATE TABLE cfg_test (id SERIAL);'].join('\n')

    const config: ResolvedConfig = {
      dialect: 'postgres',
      namespaces: {
        myns: { outputFormat: 'json', verbose: true },
      },
    }

    compile({
      source,
      filePath: 'cfg.sql',
      plugins: new Map([['myns', plugin]]),
      statements: makeStatements([{ kind: 'table', objectName: 'cfg_test', line: lineOf(source, 'CREATE') }]),
      adapter: stubAdapter,
      config,
    })

    expect(capturedCtx).not.toBe(null)
    expect(capturedCtx.config).toEqual({ outputFormat: 'json', verbose: true })
  })

  it('populates CompilerContext.namespaceTags with same-namespace tags on same object', () => {
    let capturedCtx: any = null

    const plugin = makePlugin({
      name: 'multi',
      tags: { first: {}, second: { args: [{ type: 'number' }] } },
      generateSQL: (ctx) => {
        if (ctx.tag.name === 'first') capturedCtx = ctx
        return []
      },
    })

    const source = ['-- @multi.first', '-- @multi.second(42)', 'CREATE TABLE nstags (id SERIAL);'].join('\n')

    compile({
      source,
      filePath: 'nstags.sql',
      plugins: new Map([['multi', plugin]]),
      statements: makeStatements([{ kind: 'table', objectName: 'nstags', line: lineOf(source, 'CREATE') }]),
      adapter: stubAdapter,
      config: { dialect: 'postgres' },
    })

    expect(capturedCtx).not.toBe(null)
    expect(capturedCtx.namespaceTags).toHaveLength(2)
    expect(capturedCtx.namespaceTags.some((t: any) => t.tag === 'first')).toBeTruthy()
    expect(capturedCtx.namespaceTags.some((t: any) => t.tag === 'second')).toBeTruthy()
  })

  it('correctly matches column tags when blank lines separate columns inside a table', () => {
    const contexts: any[] = []

    const plugin = makePlugin({
      name: 'ns',
      tags: { mark: {} },
      generateSQL: (ctx) => {
        contexts.push({ target: ctx.target, objectName: ctx.objectName, columnName: ctx.columnName })
        return [{ sql: `-- marked ${ctx.columnName ?? ctx.objectName}` }]
      },
    })

    const source = [
      '-- @ns.mark',
      'CREATE TABLE items (',
      '    id SERIAL PRIMARY KEY,',
      '',
      '    -- @ns.mark',
      '    name TEXT NOT NULL,',
      '',
      '    -- @ns.mark',
      '    price INTEGER',
      ');',
    ].join('\n')

    const _result = compile({
      source,
      filePath: 'blank-lines.sql',
      plugins: new Map([['ns', plugin]]),
      statements: makeStatements([
        {
          kind: 'table',
          objectName: 'items',
          line: lineOf(source, 'CREATE TABLE items'),
          columns: [
            { name: 'id', dataType: 'serial', line: lineOf(source, 'id SERIAL'), raw: null },
            { name: 'name', dataType: 'text', line: lineOf(source, 'name TEXT'), raw: null },
            { name: 'price', dataType: 'integer', line: lineOf(source, 'price INTEGER'), raw: null },
          ],
        },
      ]),
      adapter: stubAdapter,
      config: { dialect: 'postgres' },
    })

    // First tag is above CREATE TABLE -- should be table-level
    expect(contexts[0].target).toBe('table')
    expect(contexts[0].objectName).toBe('items')
    // Second tag (after blank line) should match 'name' column
    expect(contexts[1].target).toBe('column')
    expect(contexts[1].columnName).toBe('name')
    // Third tag (after blank line) should match 'price' column
    expect(contexts[2].target).toBe('column')
    expect(contexts[2].columnName).toBe('price')
  })

  it('catches generator errors and reports in CompilerOutput.errors without crashing', () => {
    const plugin = makePlugin({
      name: 'err',
      tags: { boom: {} },
      generateSQL: () => {
        throw new Error('generator exploded')
      },
      generateCode: () => {
        throw new Error('codegen failed')
      },
    })

    const source = ['-- @err.boom', 'CREATE TABLE broken (id SERIAL);'].join('\n')

    const result = compile({
      source,
      filePath: 'err.sql',
      plugins: new Map([['err', plugin]]),
      statements: makeStatements([{ kind: 'table', objectName: 'broken', line: lineOf(source, 'CREATE') }]),
      adapter: stubAdapter,
      config: { dialect: 'postgres' },
    })

    expect(result.errors.length >= 1).toBeTruthy()
    expect(
      result.errors.some((e: any) => e.namespace === 'err' && e.message.includes('generator exploded')),
    ).toBeTruthy()
    // Should not have any outputs from the errored generators
    expect(result.sqlOutputs).toHaveLength(0)
    expect(result.codeOutputs).toHaveLength(0)
  })

  it('returns empty outputs with no crash when plugins have no generators', () => {
    const plugin = makePlugin({
      name: 'passive',
      tags: { info: {} },
      // No generateSQL or generateCode
    })

    const source = ['-- @passive.info', 'CREATE TABLE inert (id SERIAL);'].join('\n')

    const result = compile({
      source,
      filePath: 'inert.sql',
      plugins: new Map([['passive', plugin]]),
      statements: makeStatements([{ kind: 'table', objectName: 'inert', line: lineOf(source, 'CREATE') }]),
      adapter: stubAdapter,
      config: { dialect: 'postgres' },
    })

    expect(result.sqlOutputs).toHaveLength(0)
    expect(result.codeOutputs).toHaveLength(0)
    expect(result.errors).toHaveLength(0)
    expect(result.sourceFile).toBe('inert.sql')
    // mergedSql should be just the original source when no SQL generated
    expect(result.mergedSql).toBe(source)
  })
})
