<?php
// Generated by @sqldoc/templates/php-eloquent -- DO NOT EDIT

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * Adoption
 *
 * @property int $id
 * @property int $pet_id
 * @property int $owner_id
 * @property string $adopted_at
 * @property float $adoption_fee
 */
class Adoption extends Model
{
    protected $table = 'adoptions';

    public $timestamps = false;

    protected $fillable = [
        'pet_id',
        'owner_id',
        'adopted_at',
        'adoption_fee',
    ];

    protected $casts = [
        'pet_id' => 'integer',
        'owner_id' => 'integer',
        'adopted_at' => 'datetime',
        'adoption_fee' => 'decimal:2',
    ];

    public function owner(): BelongsTo
    {
        return $this->belongsTo(Owner::class);
    }

    public function pet(): BelongsTo
    {
        return $this->belongsTo(Pet::class);
    }

}
