<?php
// Generated by @sqldoc/templates/php-eloquent -- DO NOT EDIT

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * LegacyInventory
 *
 * @property int $id
 * @property ?string $item_name
 * @property ?string $old_sku
 * @property ?int $quantity
 */
class LegacyInventory extends Model
{
    protected $table = 'legacy_inventory';

    public $timestamps = false;

    protected $fillable = [
        'item_name',
        'old_sku',
        'quantity',
    ];

    protected $casts = [
        'quantity' => 'integer',
    ];

}
