<?php
// Generated by @sqldoc/templates/php-eloquent -- DO NOT EDIT

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * Owner
 *
 * @property int $id
 * @property string $name
 * @property string $email
 * @property ?string $phone
 * @property ?string $created_at
 */
class Owner extends Model
{
    protected $table = 'owners';

    public $timestamps = false;

    protected $fillable = [
        'name',
        'email',
        'phone',
        'created_at',
    ];

    public function adoptions(): HasMany
    {
        return $this->hasMany(Adoption::class);
    }

}
