// Generated by @sqldoc/templates/zod -- DO NOT EDIT

import { z } from 'zod'

export const adoptionSchema = z.object({
  id: z.number(),
  petId: z.number(),
  ownerId: z.number(),
  adoptedAt: z.unknown(),
  adoptionFee: z.unknown(),
  updatedBy: z.unknown().optional(),
})

export type Adoption = z.infer<typeof adoptionSchema>

export const adoptionsauditlogSchema = z.object({
  id: z.number(),
  tableName: z.unknown(),
  operation: z.unknown(),
  oldData: z.unknown().optional(),
  newData: z.unknown().optional(),
  changedAt: z.unknown(),
})

export type AdoptionsAuditLog = z.infer<typeof adoptionsauditlogSchema>

export const categorySchema = z.object({
  id: z.number(),
  name: z.unknown().min(1),
  description: z.unknown().optional(),
})

export type Category = z.infer<typeof categorySchema>

export const legacyinventorySchema = z.object({
  id: z.number(),
  itemName: z.unknown().optional(),
  oldSku: z.unknown().optional(),
  quantity: z.number().optional(),
})

export type LegacyInventory = z.infer<typeof legacyinventorySchema>

export const locationSchema = z.object({
  id: z.number(),
  name: z.unknown(),
  address: z.unknown(),
  city: z.unknown(),
  zip: z.unknown().optional(),
})

export type Location = z.infer<typeof locationSchema>

export const medicalrecordSchema = z.object({
  id: z.number(),
  petId: z.number(),
  visitDate: z.string(),
  diagnosis: z.unknown(),
  treatment: z.unknown().optional(),
  vetName: z.unknown().optional(),
})

export type MedicalRecord = z.infer<typeof medicalrecordSchema>

export const ownerSchema = z.object({
  id: z.number(),
  name: z.unknown().min(1),
  email: z.unknown(),
  phone: z.unknown().min(7).max(20).optional(),
  createdAt: z.unknown().optional(),
})

export type Owner = z.infer<typeof ownerSchema>

export const petSchema = z.object({
  id: z.number(),
  categoryId: z.number().optional(),
  name: z.unknown().min(1),
  sku: z.unknown(),
  price: z.unknown().min(0).max(99999),
  internalNotes: z.unknown().optional(),
  status: z.unknown(),
  createdAt: z.unknown().optional(),
})

export type Pet = z.infer<typeof petSchema>

export const reviewSchema = z.object({
  id: z.number(),
  petId: z.number(),
  ownerId: z.number(),
  rating: z.number(),
  body: z.unknown().min(1).max(5).optional(),
  locationId: z.number().optional(),
  createdAt: z.unknown().optional(),
})

export type Review = z.infer<typeof reviewSchema>

export const staffauditlogSchema = z.object({
  id: z.number(),
  tableName: z.unknown(),
  operation: z.unknown(),
  oldData: z.unknown().optional(),
  newData: z.unknown().optional(),
  changedAt: z.unknown(),
})

export type StaffAuditLog = z.infer<typeof staffauditlogSchema>

export const getadoptionreportInputSchema = z.object({
  pOwnerId: z.number(),
})

export const getadoptionreportOutputSchema = z.void()
