import { defineTemplate } from '@sqldoc/ns-codegen'
import { activeTables, enrichRealm } from '../helpers/enrich.ts'
import { toPascalCase, toScreamingSnake } from '../helpers/naming.ts'

const PG_TO_PROTO: Record<string, string> = {
  smallint: 'int32',
  int2: 'int32',
  integer: 'int32',
  int: 'int32',
  int4: 'int32',
  bigint: 'int64',
  int8: 'int64',
  serial: 'int32',
  serial4: 'int32',
  bigserial: 'int64',
  serial8: 'int64',
  smallserial: 'int32',
  serial2: 'int32',
  real: 'float',
  float4: 'float',
  'double precision': 'double',
  float8: 'double',
  numeric: 'string',
  decimal: 'string',
  money: 'string',
  text: 'string',
  varchar: 'string',
  'character varying': 'string',
  char: 'string',
  character: 'string',
  name: 'string',
  citext: 'string',
  boolean: 'bool',
  bool: 'bool',
  timestamp: 'google.protobuf.Timestamp',
  'timestamp without time zone': 'google.protobuf.Timestamp',
  timestamptz: 'google.protobuf.Timestamp',
  'timestamp with time zone': 'google.protobuf.Timestamp',
  date: 'string',
  time: 'string',
  'time without time zone': 'string',
  timetz: 'string',
  interval: 'string',
  bytea: 'bytes',
  json: 'string',
  jsonb: 'string',
  uuid: 'string',
  inet: 'string',
  xml: 'string',
}

function pgToProto(pgType: string): { type: string; repeated: boolean } {
  const normalized = pgType.toLowerCase().trim()

  if (normalized.endsWith('[]')) {
    return { type: pgToProto(normalized.slice(0, -2)).type, repeated: true }
  }
  if (normalized.startsWith('_')) {
    return { type: pgToProto(normalized.slice(1)).type, repeated: true }
  }

  const base = normalized.replace(/\(\d+(?:,\s*\d+)?\)/, '').trim()
  return { type: PG_TO_PROTO[base] ?? 'string', repeated: false }
}

export default defineTemplate({
  name: 'Protocol Buffers',
  description: 'Generate Protocol Buffers message definitions from SQL schema',
  language: 'protobuf',

  generate(ctx) {
    const schema = enrichRealm(ctx)
    const allColumns = [...schema.tables.flatMap((t) => t.columns), ...schema.views.flatMap((v) => v.columns)]
    const needsTimestamp = allColumns.some((c) => {
      const base = c.pgType
        .toLowerCase()
        .replace(/\(\d+(?:,\s*\d+)?\)/, '')
        .trim()
      return base.startsWith('timestamp')
    })

    const lines: string[] = [
      '// Generated by @sqldoc/templates/protobuf -- DO NOT EDIT',
      'syntax = "proto3";',
      '',
      'package schema;',
      '',
    ]

    if (needsTimestamp) {
      lines.push('import "google/protobuf/timestamp.proto";')
      lines.push('')
    }

    // Enums
    for (const e of schema.enums) {
      const enumName = toPascalCase(e.name)
      lines.push(`enum ${enumName} {`)
      lines.push(`  ${toScreamingSnake(e.name)}_UNSPECIFIED = 0;`)
      e.values.forEach((v, i) => {
        lines.push(`  ${toScreamingSnake(e.name)}_${toScreamingSnake(v)} = ${i + 1};`)
      })
      lines.push('}')
      lines.push('')
    }

    // Composite types as messages
    const composites = new Map<string, Array<{ name: string; type: string }>>()
    for (const table of schema.tables) {
      for (const col of table.columns) {
        if (col.category === 'composite' && col.compositeFields?.length && !composites.has(col.pgType)) {
          composites.set(col.pgType, col.compositeFields)
        }
      }
    }
    for (const fn of schema.functions) {
      if (fn.returnType?.category === 'composite' && fn.returnType.compositeFields?.length) {
        const typeName = fn.returnType.type.replace(/^setof\s+/i, '')
        if (!composites.has(typeName)) {
          composites.set(typeName, fn.returnType.compositeFields)
        }
      }
    }
    for (const [name, fields] of composites) {
      const msgName = toPascalCase(name)
      lines.push(`message ${msgName} {`)
      let fieldNum = 1
      for (const f of fields) {
        const { type, repeated } = pgToProto(f.type)
        const prefix = repeated ? 'repeated ' : ''
        lines.push(`  ${prefix}${type} ${f.name} = ${fieldNum};`)
        fieldNum++
      }
      lines.push('}')
      lines.push('')
    }

    for (const table of activeTables(schema)) {
      lines.push(`message ${table.pascalName} {`)

      let fieldNum = 1
      for (const col of table.columns) {
        if (col.category === 'enum' && col.enumValues?.length) {
          const enumType = toPascalCase(col.pgType)
          const prefix = col.nullable ? 'optional ' : ''
          lines.push(`  ${prefix}${enumType} ${col.name} = ${fieldNum};`)
        } else if (col.category === 'composite' && col.compositeFields?.length) {
          const compositeType = toPascalCase(col.pgType)
          const prefix = col.nullable ? 'optional ' : ''
          lines.push(`  ${prefix}${compositeType} ${col.name} = ${fieldNum};`)
        } else {
          const { type, repeated } = pgToProto(col.pgType)
          const prefix = repeated ? 'repeated ' : col.nullable ? 'optional ' : ''
          lines.push(`  ${prefix}${type} ${col.name} = ${fieldNum};`)
        }
        fieldNum++
      }

      lines.push('}')
      lines.push('')
    }

    // Views (read-only)
    for (const view of schema.views.filter((v) => !v.skipped)) {
      lines.push(`// Read-only (from view)`)
      lines.push(`message ${view.pascalName} {`)

      let fieldNum = 1
      for (const col of view.columns) {
        if (col.category === 'enum' && col.enumValues?.length) {
          const enumType = toPascalCase(col.pgType)
          const prefix = col.nullable ? 'optional ' : ''
          lines.push(`  ${prefix}${enumType} ${col.name} = ${fieldNum};`)
        } else if (col.category === 'composite' && col.compositeFields?.length) {
          const compositeType = toPascalCase(col.pgType)
          const prefix = col.nullable ? 'optional ' : ''
          lines.push(`  ${prefix}${compositeType} ${col.name} = ${fieldNum};`)
        } else {
          const { type, repeated } = pgToProto(col.pgType)
          const prefix = repeated ? 'repeated ' : col.nullable ? 'optional ' : ''
          lines.push(`  ${prefix}${type} ${col.name} = ${fieldNum};`)
        }
        fieldNum++
      }

      lines.push('}')
      lines.push('')
    }

    // Functions (skip trigger functions)
    for (const fn of schema.functions) {
      const retRaw = fn.returnType?.type?.toLowerCase() ?? ''
      if (retRaw === 'trigger') continue

      // Request message
      const reqName = `${fn.pascalName}Request`
      lines.push(`message ${reqName} {`)
      let fieldNum = 1
      for (const a of fn.args.filter((a) => !a.name?.startsWith('_') && (a as any).mode !== 'OUT')) {
        const { type, repeated } = pgToProto(a.type)
        const prefix = repeated ? 'repeated ' : ''
        lines.push(`  ${prefix}${type} ${a.name || 'arg'} = ${fieldNum};`)
        fieldNum++
      }
      lines.push('}')
      lines.push('')

      // Response message
      const respName = `${fn.pascalName}Response`
      lines.push(`message ${respName} {`)
      if (retRaw.startsWith('setof ')) {
        const tableName = retRaw.replace('setof ', '')
        const table = schema.tables.find((t) => t.name === tableName || t.sqlName === tableName)
        const retType = table
          ? table.pascalName
          : composites.has(tableName)
            ? toPascalCase(tableName)
            : pgToProto(tableName).type
        lines.push(`  repeated ${retType} results = 1;`)
      } else if (fn.returnType) {
        const { type, repeated } = pgToProto(fn.returnType.type)
        const prefix = repeated ? 'repeated ' : ''
        lines.push(`  ${prefix}${type} result = 1;`)
      }
      lines.push('}')
      lines.push('')
    }

    return { files: [{ path: 'schema.proto', content: lines.join('\n') }] }
  },
})
