// Generated by @sqldoc/templates/kysely -- DO NOT EDIT

import { sql, type Kysely, type Generated } from 'kysely'

export type JsonPrimitive = string | number | boolean | null
export type JsonArray = JsonValue[]
export type JsonObject = { [key: string]: JsonValue | undefined }
export type JsonValue = JsonPrimitive | JsonArray | JsonObject
export type Json = JsonValue

export interface AdoptionReport {
  petName: string
  ownerName: string
  adoptedAt: Date
  adoptionFee: string
  categoryName: string
}

export interface Adoption {
  id: Generated<number>
  pet_id: number
  owner_id: number
  adopted_at: Generated<Date>
  adoption_fee: Generated<string>
}

export interface AdoptionsAuditLog {
  id: Generated<number>
  table_name: string
  operation: string
  old_data: Json | null
  new_data: Json | null
  changed_at: Generated<Date>
}

export interface Category {
  id: Generated<number>
  name: string
  description: string | null
}

export interface LegacyInventory {
  id: Generated<number>
  item_name: string | null
  old_sku: string | null
  quantity: Generated<number | null>
}

export interface Location {
  id: Generated<number>
  name: string
  address: string
  city: string
  zip: string | null
}

export interface MedicalRecord {
  id: Generated<number>
  pet_id: number
  visit_date: Generated<string>
  diagnosis: string
  treatment: string | null
  vet_name: string | null
}

export interface Owner {
  id: Generated<number>
  name: string
  email: string
  phone: string | null
  created_at: Generated<Date | null>
}

export interface Pet {
  id: Generated<number>
  category_id: number | null
  name: string
  sku: string
  price: Generated<string>
  internal_notes: string | null
  status: Generated<string>
  created_at: Generated<Date | null>
}

export interface Review {
  id: Generated<number>
  pet_id: number
  owner_id: number
  rating: number
  body: string | null
  location_id: number | null
  created_at: Generated<Date | null>
}

export interface StaffAuditLog {
  id: Generated<number>
  table_name: string
  operation: string
  old_data: Json | null
  new_data: Json | null
  changed_at: Generated<Date>
}

export interface Database {
  'adoptions': Adoption
  'adoptions_audit_log': AdoptionsAuditLog
  'categories': Category
  'legacy_inventory': LegacyInventory
  'locations': Location
  'medical_records': MedicalRecord
  'owners': Owner
  'pets': Pet
  'reviews': Review
  'staff_audit_log': StaffAuditLog
}

export function getAdoptionReport(db: Kysely<Database>, pOwnerId: number) {
  return db.selectFrom(sql<AdoptionReport>`"get_adoption_report"(${pOwnerId})`.as('t')).selectAll().execute()
}
