import { defineTemplate } from '@sqldoc/ns-codegen'
import { activeTables, type EnrichedColumn, enrichRealm } from '../helpers/enrich.ts'

/**
 * Map PG types to COBOL PIC clauses.
 * COBOL uses PIC (Picture) clauses to define data formats:
 *   PIC X(n)    = alphanumeric, n characters
 *   PIC 9(n)    = numeric, n digits
 *   PIC S9(n)   = signed numeric
 *   PIC 9(n)V9(m) = numeric with implied decimal
 */
function pgToCoboPic(col: EnrichedColumn): string {
  const pgType = col.pgType
    .toLowerCase()
    .replace(/\(\d+(?:,\s*\d+)?\)/, '')
    .trim()

  switch (pgType) {
    // Integers
    case 'smallint':
    case 'int2':
      return 'PIC S9(4) COMP.'
    case 'integer':
    case 'int':
    case 'int4':
    case 'serial':
    case 'serial4':
      return 'PIC S9(9) COMP.'
    case 'bigint':
    case 'int8':
    case 'bigserial':
    case 'serial8':
      return 'PIC S9(18) COMP.'
    case 'smallserial':
    case 'serial2':
      return 'PIC S9(4) COMP.'

    // Floats -- use COMP-2 (double precision float)
    case 'real':
    case 'float4':
      return 'COMP-1.'
    case 'double precision':
    case 'float8':
      return 'COMP-2.'

    // Decimal -- use implied decimal point
    case 'numeric':
    case 'decimal':
    case 'money': {
      const m = col.pgType.match(/\((\d+)(?:,\s*(\d+))?\)/)
      const prec = m ? Number.parseInt(m[1], 10) : 10
      const scale = m?.[2] ? Number.parseInt(m[2], 10) : 2
      return `PIC S9(${prec - scale})V9(${scale}) COMP-3.`
    }

    // Boolean -- single character Y/N
    case 'boolean':
    case 'bool':
      return "PIC X VALUE 'N'."

    // Date/time
    case 'date':
      return 'PIC 9(8).' // YYYYMMDD
    case 'time':
    case 'time without time zone':
    case 'timetz':
    case 'time with time zone':
      return 'PIC 9(6).' // HHMMSS
    case 'timestamp':
    case 'timestamp without time zone':
    case 'timestamptz':
    case 'timestamp with time zone':
      return 'PIC X(26).' // ISO 8601 string
    case 'interval':
      return 'PIC X(30).'

    // Text -- estimate from varchar length or default to 255
    case 'varchar':
    case 'character varying': {
      const lenMatch = col.pgType.match(/\((\d+)\)/)
      const len = lenMatch ? Number.parseInt(lenMatch[1], 10) : 255
      return `PIC X(${len}).`
    }
    case 'char':
    case 'character': {
      const lenMatch = col.pgType.match(/\((\d+)\)/)
      const len = lenMatch ? Number.parseInt(lenMatch[1], 10) : 1
      return `PIC X(${len}).`
    }
    case 'text':
    case 'citext':
    case 'name':
      return 'PIC X(255).'

    // UUID -- 36 char string (8-4-4-4-12)
    case 'uuid':
      return 'PIC X(36).'

    // Binary/JSON/other -- treat as large string
    case 'bytea':
    case 'json':
    case 'jsonb':
    case 'xml':
      return 'PIC X(4096).'

    default:
      return 'PIC X(255).'
  }
}

// COBOL reserved words that can't be used as data names
const COBOL_RESERVED = new Set([
  'ADDRESS',
  'ID',
  'CONTENT',
  'STATUS',
  'NAME',
  'TYPE',
  'VALUE',
  'SIZE',
  'COUNT',
  'DATE',
  'TIME',
  'DATA',
  'FILE',
  'KEY',
  'RECORD',
  'TABLE',
  'INDEX',
  'INPUT',
  'OUTPUT',
  'OPEN',
  'CLOSE',
  'READ',
  'WRITE',
  'DELETE',
])

function toCobolName(name: string): string {
  // COBOL names are uppercase, hyphens instead of underscores, max 30 chars
  let cobol = name.toUpperCase().replace(/_/g, '-').substring(0, 30)

  // Prefix reserved words with WS- (Working Storage)
  if (COBOL_RESERVED.has(cobol)) {
    cobol = `WS-${cobol}`
  }

  return cobol
}

export default defineTemplate({
  name: 'COBOL Copybook',
  description: 'Generate COBOL copybook record definitions from SQL schema',
  language: 'cobol',

  generate(ctx) {
    const schema = enrichRealm(ctx)
    const lines: string[] = ['      *> Generated by @sqldoc/templates/cobol-copybook', '      *> DO NOT EDIT', '']

    // Enums as 88-level conditions
    for (const e of schema.enums) {
      const recordName = `${toCobolName(e.name)}-ENUM`
      lines.push(`       01  ${recordName}  PIC X(50).`)
      for (const v of e.values) {
        const condName = `${toCobolName(e.name)}-${toCobolName(v)}`
        lines.push(`           88  ${condName}  VALUE '${v}'.`)
      }
      lines.push('')
    }

    for (const table of activeTables(schema)) {
      const recordName = `${toCobolName(table.name)}-RECORD`
      lines.push(`       01  ${recordName}.`)

      for (const col of table.columns) {
        const fieldName = toCobolName(col.name)
        if (col.category === 'enum' && col.enumValues?.length) {
          // Enum column: use PIC X with 88-level conditions
          const maxLen = Math.max(...col.enumValues.map((v) => v.length), 20)
          lines.push(`           05  ${fieldName}  PIC X(${maxLen}).`)
          for (const v of col.enumValues) {
            const condName = `${fieldName}-${toCobolName(v)}`
            lines.push(`               88  ${condName}  VALUE '${v}'.`)
          }
        } else {
          const pic = pgToCoboPic(col)
          lines.push(`           05  ${fieldName}  ${pic}`)
        }
      }

      lines.push('')
    }

    // Views (read-only)
    for (const view of schema.views.filter((v) => !v.skipped && v.columns.length > 0)) {
      const recordName = `${toCobolName(view.name)}-VIEW`
      lines.push(`      *> Read-only (from view)`)
      lines.push(`       01  ${recordName}.`)

      for (const col of view.columns) {
        const fieldName = toCobolName(col.name)
        if (col.category === 'enum' && col.enumValues?.length) {
          const maxLen = Math.max(...col.enumValues.map((v) => v.length), 20)
          lines.push(`           05  ${fieldName}  PIC X(${maxLen}).`)
          for (const v of col.enumValues) {
            const condName = `${fieldName}-${toCobolName(v)}`
            lines.push(`               88  ${condName}  VALUE '${v}'.`)
          }
        } else {
          const pic = pgToCoboPic(col)
          lines.push(`           05  ${fieldName}  ${pic}`)
        }
      }

      lines.push('')
    }

    return { files: [{ path: 'schema.cpy', content: lines.join('\n') }] }
  },
})
