/**
 * Per-dialect SQL + URL helpers for shadow database management.
 *
 * A "shadow database" is an ephemeral database created on an existing server
 * (or container) for a single introspection or diff operation. Each call to
 * ShadowDbProvider.acquire() creates one; release() drops it. See shadow.ts.
 *
 * Shadow database names are always generated by newShadowDatabaseName(),
 * which emits alphanumeric identifiers with no characters that require
 * escaping in any of the three dialects.
 */

import { randomBytes } from 'node:crypto'
import type { Dialect } from './types.ts'

export interface ShadowSqlDialect {
  dialect: Dialect
  /** Maintenance database the admin adapter connects to for CREATE/DROP. */
  maintenanceDb: string
  /** SQL to create a new database given its raw name. */
  createDatabaseSql(name: string): string
  /** Statement(s) to drop a database given its raw name. */
  dropDatabaseSql(name: string): string[]
  /** Query that returns rows with a `name` column listing stale shadow databases. */
  listStaleShadowsSql(): string
  /** Rewrite the database name component of a connection URL. */
  withDatabase(url: string, dbName: string): string
  /** Extract the database name component, or undefined if the URL is server-only. */
  extractDatabase(url: string): string | undefined
  /** Permission hint surfaced when CREATE DATABASE fails. */
  permissionHint(): string
}

/** Shadow DB identifier. Alphanumeric + underscore only — safe for all dialects. */
export function newShadowDatabaseName(): string {
  const rand = randomBytes(4).toString('hex')
  return `sqldoc_shadow_${Date.now()}_${rand}`
}

/** How old a shadow must be before we consider it stale. */
const STALE_THRESHOLD_MS = 10_000

/** Extract the creation timestamp from a shadow name, or null if it doesn't parse. */
export function shadowCreatedAt(name: string): number | null {
  const match = name.match(/^sqldoc_shadow_(\d+)_/)
  return match ? Number.parseInt(match[1], 10) : null
}

/** Return true if the shadow name is older than the stale threshold. */
export function isStaleShadow(name: string): boolean {
  const ts = shadowCreatedAt(name)
  if (ts == null) return false
  return Date.now() - ts > STALE_THRESHOLD_MS
}

function pathnameToDb(pathname: string): string | undefined {
  const trimmed = pathname.replace(/^\//, '')
  return trimmed.length > 0 ? decodeURIComponent(trimmed) : undefined
}

function withDatabaseUrl(url: string, dbName: string): string {
  const u = new URL(url)
  u.pathname = `/${encodeURIComponent(dbName)}`
  return u.toString()
}

function extractDatabaseUrl(url: string): string | undefined {
  return pathnameToDb(new URL(url).pathname)
}

// ── Postgres ───────────────────────────────────────────────────────

const postgresDialect: ShadowSqlDialect = {
  dialect: 'postgres',
  maintenanceDb: 'postgres',
  createDatabaseSql: (name) => `CREATE DATABASE "${name}"`,
  dropDatabaseSql: (name) => [`DROP DATABASE IF EXISTS "${name}" WITH (FORCE)`],
  listStaleShadowsSql: () => `
    SELECT d.datname AS name FROM pg_database d
    WHERE d.datname LIKE 'sqldoc_shadow_%'
    AND NOT EXISTS (SELECT 1 FROM pg_stat_activity a WHERE a.datname = d.datname)
  `,
  withDatabase: withDatabaseUrl,
  extractDatabase: extractDatabaseUrl,
  permissionHint() {
    return 'the Postgres role needs the CREATEDB attribute: ALTER ROLE <user> CREATEDB;'
  },
}

// ── MySQL ──────────────────────────────────────────────────────────

const mysqlDialect: ShadowSqlDialect = {
  dialect: 'mysql',
  maintenanceDb: 'mysql',
  createDatabaseSql: (name) => `CREATE DATABASE \`${name}\``,
  dropDatabaseSql: (name) => [`DROP DATABASE IF EXISTS \`${name}\``],
  listStaleShadowsSql: () => `
    SELECT s.schema_name AS name FROM information_schema.schemata s
    WHERE s.schema_name LIKE 'sqldoc_shadow_%'
    AND s.schema_name NOT IN (
      SELECT DISTINCT db FROM information_schema.processlist WHERE db LIKE 'sqldoc_shadow_%'
    )
  `,
  withDatabase: withDatabaseUrl,
  extractDatabase: extractDatabaseUrl,
  permissionHint() {
    return 'the MySQL user needs CREATE and DROP on *.*: GRANT CREATE, DROP ON *.* TO <user>@<host>;'
  },
}

// ── MSSQL ──────────────────────────────────────────────────────────

const mssqlDialect: ShadowSqlDialect = {
  dialect: 'mssql',
  maintenanceDb: 'master',
  createDatabaseSql: (name) => `CREATE DATABASE [${name}]`,
  dropDatabaseSql: (name) => [
    `IF DB_ID('${name}') IS NOT NULL ALTER DATABASE [${name}] SET SINGLE_USER WITH ROLLBACK IMMEDIATE`,
    `DROP DATABASE IF EXISTS [${name}]`,
  ],
  listStaleShadowsSql: () => `
    SELECT d.name FROM sys.databases d
    WHERE d.name LIKE 'sqldoc_shadow_%'
    AND d.database_id NOT IN (
      SELECT DISTINCT database_id FROM sys.dm_exec_sessions WHERE database_id IS NOT NULL
    )
  `,
  withDatabase: withDatabaseUrl,
  extractDatabase: extractDatabaseUrl,
  permissionHint() {
    return 'the MSSQL login needs the dbcreator server role: ALTER SERVER ROLE dbcreator ADD MEMBER <login>;'
  },
}

const REGISTRY: Record<Dialect, ShadowSqlDialect | undefined> = {
  postgres: postgresDialect,
  mysql: mysqlDialect,
  mssql: mssqlDialect,
  sqlite: undefined,
}

/** Get shadow helpers for a dialect. Throws for dialects without shadow support. */
export function getShadowSqlDialect(dialect: Dialect): ShadowSqlDialect {
  const d = REGISTRY[dialect]
  if (!d) {
    throw new Error(`Shadow databases are not supported for dialect '${dialect}'`)
  }
  return d
}

// ── Stale cleanup ──────────────────────────────────────────────────

export interface AdminDb {
  query(sql: string): Promise<{ columns: string[]; rows: unknown[][] }>
  exec(sql: string): Promise<{ rowsAffected: number }>
}

/**
 * Drop any shadow databases that are both idle (no active connections) and
 * older than STALE_THRESHOLD_MS. Safe to call at source startup — it won't
 * touch shadows created by other active sqldoc processes.
 */
export async function cleanupStaleShadows(admin: AdminDb, sql: ShadowSqlDialect): Promise<void> {
  try {
    const result = await admin.query(sql.listStaleShadowsSql())
    const nameIdx = result.columns.indexOf('name')
    for (const row of result.rows) {
      const name = row[nameIdx] as string
      if (!isStaleShadow(name)) continue
      for (const stmt of sql.dropDatabaseSql(name)) {
        try {
          await admin.exec(stmt)
        } catch {}
      }
      if (process.env.DEBUG) console.error(`[shadow] cleaned up stale shadow: ${name}`)
    }
  } catch {
    // Best-effort — don't block source creation if cleanup fails.
  }
}
