// Derived from Atlas by Atlas Authors, licensed under Apache 2.0
// Source: sql/sqlite/diff.go

import type { DiffDriver } from '../internal/sqlx.ts'
import { defaultValue, isUint, mayWrap } from '../internal/sqlx.ts'
import type { DiffOptions } from '../schema/inspect.ts'
import type { Change } from '../schema/migrate.ts'
import { ChangeKind } from '../schema/migrate.ts'
import type { Attr, Column, ForeignKey, Index, Realm, Schema, Table, View } from '../schema/schema.ts'
import { hasAttr, type IndexOrigin, type IndexPredicate, storedOrVirtual } from './driver.ts'

// -- SQLite DiffDriver Implementation --

/**
 * SQLite-specific diff driver.
 * Implements the DiffDriver interface for comparing SQLite schema elements.
 */
export class SqliteDiff implements DiffDriver {
  /** No special schema attribute diffing for SQLite. */
  schemaAttrDiff(_from: Schema, _to: Schema): Change[] {
    return []
  }

  /** No realm-level object changes for SQLite. */
  realmObjectDiff(_from: Realm, _to: Realm): Change[] {
    return []
  }

  /** No schema-level object changes for SQLite. */
  schemaObjectDiff(_from: Schema, _to: Schema, _opts?: DiffOptions): Change[] {
    return []
  }

  /** Compare table attributes (WITHOUT ROWID, STRICT). */
  tableAttrDiff(from: Table, to: Table, _opts?: DiffOptions): Change[] {
    const changes: Change[] = []
    for (const kind of ['without_rowid', 'strict'] as const) {
      const fromHas = hasAttr(from.attrs, kind) !== undefined
      const toHas = hasAttr(to.attrs, kind) !== undefined
      if (fromHas && !toHas) {
        changes.push({ type: 'drop_attr', A: { kind } as any })
      } else if (!fromHas && toHas) {
        changes.push({ type: 'add_attr', A: { kind } as any })
      }
    }
    return changes
  }

  /** No view attribute changes for SQLite. */
  viewAttrChanges(_from: View, _to: View): Change[] {
    return []
  }

  /**
   * Compare two columns and return a ModifyColumn change if different.
   * Note: column comments are ignored as SQLite does not support them.
   */
  columnChange(_fromTable: Table, from: Column, to: Column, _opts?: DiffOptions): Change | undefined {
    let change = ChangeKind.NoChange

    if (from.type.null !== to.type.null) {
      change |= ChangeKind.ChangeNull
    }

    if (this.typeChanged(from, to)) {
      change |= ChangeKind.ChangeType
    }

    if (this.defaultChanged(from, to)) {
      change |= ChangeKind.ChangeDefault
    }

    if (this.generatedChanged(from, to)) {
      change |= ChangeKind.ChangeGenerated
    }

    if (change === ChangeKind.NoChange) {
      return undefined
    }

    return { type: 'modify_column', from, to, change }
  }

  /**
   * Reports if the index attributes were changed.
   * Compares partial index predicates.
   */
  indexAttrChanged(from: Attr[], to: Attr[]): boolean {
    const p1 = hasAttr<IndexPredicate>(from, 'index_predicate')
    const p2 = hasAttr<IndexPredicate>(to, 'index_predicate')
    const has1 = p1 !== undefined
    const has2 = p2 !== undefined
    if (has1 !== has2) return true
    if (p1 && p2 && p1.P !== p2.P && p1.P !== mayWrap(p2.P)) return true
    return false
  }

  /** Index-part attributes are not changed in SQLite. */
  indexPartAttrChanged(_from: Index, _to: Index, _i: number): boolean {
    return false
  }

  /**
   * Reports if the index name was generated by the database.
   * See: https://github.com/sqlite/sqlite/blob/e937df8/src/build.c#L3583
   */
  isGeneratedIndexName(table: Table, index: Index): boolean {
    const prefix = `sqlite_autoindex_${table.name}_`
    if (!index.name?.startsWith(prefix)) return false
    const suffix = index.name.slice(prefix.length)
    const i = parseInt(suffix, 10)
    return !Number.isNaN(i) && i > 0
  }

  /**
   * Reports if the foreign key referential action was changed.
   * SQLite defaults to "NO ACTION" when not specified.
   */
  referenceChanged(from: string | undefined, to: string | undefined): boolean {
    const f = from || 'NO ACTION'
    const t = to || 'NO ACTION'
    return f !== t
  }

  /** FK attributes are not changed in SQLite. */
  foreignKeyAttrChanged(_from: Attr[], _to: Attr[]): boolean {
    return false
  }

  /** Reports if the column is a generated/virtual column. */
  isGeneratedColumn(col: Column): boolean {
    if (!col.attrs) return false
    return col.attrs.some((a) => 'kind' in a && (a as any).kind === 'generated')
  }

  /**
   * Normalize table before diffing.
   * Handles FK constraint name matching and index name normalization.
   */
  normalize(table: Table): void {
    // Normalize auto-generated index names.
    for (const idx of table.indexes ?? []) {
      normalizeIdxName(idx, table)
    }
  }

  // -- Private Methods --

  /**
   * Reports if the column type was changed.
   * Uses type affinity comparison (kind-based).
   */
  private typeChanged(from: Column, to: Column): boolean {
    const fromT = from.type.type
    const toT = to.type.type
    if (!fromT || !toT) return false

    // For unsupported (user-defined) types, compare the T string.
    if (fromT.kind === 'unsupported' && toT.kind === 'unsupported') {
      return fromT.T !== toT.T
    }
    if (fromT.kind === 'unsupported' || toT.kind === 'unsupported') {
      return true
    }

    // Types are mismatched if they do not have the same kind (type affinity).
    return fromT.kind !== toT.kind
  }

  /** Reports if the default value of a column was changed. */
  private defaultChanged(from: Column, to: Column): boolean {
    const d1 = defaultValue(from)
    const d2 = defaultValue(to)
    const ok1 = d1 !== undefined
    const ok2 = d2 !== undefined
    if (ok1 !== ok2) return true
    if (d1 === d2) return false

    // Try unquoting for comparison.
    const x1 = unquote(d1 ?? '')
    const x2 = unquote(d2 ?? '')
    return x1 !== x2
  }

  /** Reports if the generated expression of a column was changed. */
  private generatedChanged(from: Column, to: Column): boolean {
    const fromGen = from.attrs?.find((a) => 'kind' in a && (a as any).kind === 'generated') as
      | { expr: string; type?: string }
      | undefined
    const toGen = to.attrs?.find((a) => 'kind' in a && (a as any).kind === 'generated') as
      | { expr: string; type?: string }
      | undefined

    const fromHas = fromGen !== undefined
    const toHas = toGen !== undefined

    if (fromHas !== toHas) return true
    if (!fromHas || !fromGen || !toGen) return false

    return (
      mayWrap(fromGen.expr) !== mayWrap(toGen.expr) || storedOrVirtual(fromGen.type) !== storedOrVirtual(toGen.type)
    )
  }
}

// -- Index Name Normalization --

/**
 * Normalize index names before generating CREATE INDEX.
 * SQLite auto-generates index names like "sqlite_autoindex_tablename_N"
 * for PRIMARY KEY and UNIQUE constraints. These cannot be created manually
 * with such names, so we rename them to "Table_Column1_Column2" format.
 */
function normalizeIdxName(idx: Index, t: Table): void {
  if (!idx.name?.startsWith('sqlite_autoindex')) return

  const origin = hasAttr<IndexOrigin>(idx.attrs, 'index_origin')
  if (origin && origin.O === 'p') return

  // Use the format: <Table>_<Columns>
  const names = [t.name]
  for (const p of idx.parts) {
    if (!p.column) continue
    names.push(p.column)
  }
  idx.name = names.join('_')
}

/**
 * Normalize FK constraint names between two tables.
 * In SQLite, FK names are hard to get (require parsing CREATE TABLE).
 * Match FKs by their properties rather than by name.
 */
export function normalizeFKs(from: Table, to: Table): void {
  const used = new Array(to.foreignKeys?.length ?? 0).fill(false)

  for (const fk1 of from.foreignKeys ?? []) {
    for (let i = 0; i < (to.foreignKeys?.length ?? 0); i++) {
      if (used[i]) continue
      const fk2 = to.foreignKeys![i]
      if ((fk2.symbol === fk1.symbol && !isUint(fk1.symbol ?? '')) || sameFK(fk1, fk2)) {
        fk1.symbol = fk2.symbol
        used[i] = true
      }
    }
  }
}

/** Check if two FKs have identical properties (columns, ref table, ref columns). */
function sameFK(fk1: ForeignKey, fk2: ForeignKey): boolean {
  if (
    fk1.refTable !== fk2.refTable ||
    fk1.columns.length !== fk2.columns.length ||
    fk1.refColumns.length !== fk2.refColumns.length
  ) {
    return false
  }
  for (let i = 0; i < fk1.columns.length; i++) {
    if (fk1.columns[i] !== fk2.columns[i]) return false
  }
  for (let i = 0; i < fk1.refColumns.length; i++) {
    if (fk1.refColumns[i] !== fk2.refColumns[i]) return false
  }
  return true
}

/** Try to unquote a string value. Returns the original if not quoted. */
function unquote(s: string): string {
  if (s.length < 2) return s
  if ((s[0] === "'" && s[s.length - 1] === "'") || (s[0] === '"' && s[s.length - 1] === '"')) {
    return s.slice(1, -1)
  }
  return s
}
