import { defineTemplate } from '@sqldoc/ns-codegen'
import { activeTables, enrichRealm } from '../helpers/enrich.ts'
import { toCamelCase, toPascalCase } from '../helpers/naming.ts'
import { JSON_TYPE_DECLARATION, pgToTs, type TsTypeOptions } from '../types/pg-to-ts.ts'

export const configSchema = {
  dateType: {
    type: 'enum',
    values: ['Date', 'dayjs', 'luxon', 'string'],
    description: 'How to represent date/time types',
  },
  bigintType: {
    type: 'enum',
    values: ['number', 'bigint', 'string'],
    description: 'How to represent bigint/bigserial columns',
  },
} as const

export default defineTemplate({
  name: 'Knex Table Types',
  description: 'Generate TypeScript table interfaces with Knex module augmentation for type-safe queries',
  language: 'typescript',
  configSchema,

  generate(ctx) {
    const config = ctx.config ?? {}
    const options: TsTypeOptions = {
      dateType: config.dateType,
      bigintType: config.bigintType,
      nullableStyle: 'null-union',
    }

    const schema = enrichRealm(ctx)
    const allCols = [...schema.tables, ...schema.views].flatMap((t) => t.columns)
    const hasJson = allCols.some((c) => c.category === 'json' || c.pgType === 'json' || c.pgType === 'jsonb')

    const lines: string[] = [
      '// Generated by @sqldoc/templates/knex -- DO NOT EDIT',
      '',
      "import type { Knex } from 'knex'",
      '',
    ]

    if (hasJson) {
      lines.push(JSON_TYPE_DECLARATION)
      lines.push('')
    }

    // Enums
    for (const e of schema.enums) {
      const values = e.values.map((v) => `'${v}'`).join(' | ')
      lines.push(`export type ${e.pascalName} = ${values}`)
      lines.push('')
    }

    // Composite types (collected from columns)
    const composites = new Map<string, Array<{ name: string; type: string }>>()
    for (const table of schema.tables) {
      for (const col of table.columns) {
        if (col.category === 'composite' && col.compositeFields?.length && !composites.has(col.pgType)) {
          composites.set(col.pgType, col.compositeFields)
        }
      }
    }
    for (const [name, fields] of composites) {
      const typeName = toPascalCase(name)
      lines.push(`export interface ${typeName} {`)
      for (const f of fields) {
        lines.push(`  ${toCamelCase(f.name)}: ${pgToTs(f.type, false, options)}`)
      }
      lines.push('}')
      lines.push('')
    }

    // Generate per-table interfaces
    const tableEntries: string[] = []

    for (const table of activeTables(schema)) {
      const interfaceName = `${table.pascalName}Table`

      lines.push(`export interface ${interfaceName} {`)

      for (const col of table.columns) {
        const tsType = resolveType(col, options)
        lines.push(`  ${col.name}: ${tsType}`)
      }

      lines.push('}')
      lines.push('')

      tableEntries.push(`    '${table.sqlName}': ${interfaceName}`)
    }

    // Views (read-only)
    const viewEntries: string[] = []

    for (const view of schema.views.filter((v) => !v.skipped)) {
      const interfaceName = `${view.pascalName}View`

      lines.push(`/** Read-only (from view) */`)
      lines.push(`export interface ${interfaceName} {`)

      for (const col of view.columns) {
        const tsType = resolveType(col, options)
        lines.push(`  ${col.name}: ${tsType}`)
      }

      lines.push('}')
      lines.push('')

      viewEntries.push(`    '${view.sqlName}': ${interfaceName}`)
    }

    // Knex module augmentation for type-safe table map
    lines.push("declare module 'knex/types/tables' {")
    lines.push('  interface Tables {')
    for (const entry of tableEntries) {
      lines.push(entry)
    }
    for (const entry of viewEntries) {
      lines.push(entry)
    }
    lines.push('  }')
    lines.push('}')
    lines.push('')

    // Functions (skip trigger functions)
    for (const fn of schema.functions) {
      const retRaw = fn.returnType?.type?.toLowerCase() ?? ''
      if (retRaw === 'trigger') continue

      const params = fn.args
        .filter((a) => !a.name?.startsWith('_') && (a as any).mode !== 'OUT')
        .map((a) => {
          const argType = pgToTs(a.type, false, options, a.category as any)
          return `${toCamelCase(a.name || 'arg')}: ${argType}`
        })
        .join(', ')

      let retType: string
      if (retRaw.startsWith('setof ')) {
        const tableName = retRaw.replace('setof ', '')
        const table = schema.tables.find((t) => t.name === tableName || t.sqlName === tableName)
        retType = table ? `${table.pascalName}Table[]` : `${pgToTs(tableName, false, options)}[]`
      } else if (fn.returnType) {
        retType = pgToTs(fn.returnType.type, false, options, fn.returnType.category as any)
      } else {
        retType = 'void'
      }

      lines.push(`export type ${fn.pascalName} = (${params}) => ${retType}`)
      lines.push('')
    }

    return {
      files: [
        {
          path: 'database.ts',
          content: lines.join('\n'),
        },
      ],
    }

    function resolveType(col: any, options: TsTypeOptions): string {
      if (col.typeOverride) return col.typeOverride
      if (col.category === 'enum' && col.enumValues?.length) {
        return col.nullable ? `${toPascalCase(col.pgType)} | null` : toPascalCase(col.pgType)
      }
      if (col.category === 'composite' && col.compositeFields?.length) {
        const compositeType = toPascalCase(col.pgType)
        return col.nullable ? `${compositeType} | null` : compositeType
      }
      return pgToTs(col.pgType, col.nullable, options, col.category)
    }
  },
})
