import { defineTemplate } from '@sqldoc/ns-codegen'
import { activeTables, enrichRealm } from '../helpers/enrich.ts'
import {
  collectCompositeTypes,
  emitCompositeInterfaces,
  hasJsonTypes,
  inputFunctionParams,
  resolveFunctionReturnType,
  resolveTsColumnType,
} from '../helpers/typescript.ts'
import { JSON_TYPE_DECLARATION, type TsTypeOptions } from '../types/pg-to-ts.ts'

export const configSchema = {
  dateType: {
    type: 'enum',
    values: ['Date', 'dayjs', 'luxon', 'string'],
    description: 'How to represent date/time types',
  },
  bigintType: {
    type: 'enum',
    values: ['number', 'bigint', 'string'],
    description: 'How to represent bigint/bigserial columns',
  },
} as const

export default defineTemplate({
  name: 'Knex Table Types',
  description: 'Generate TypeScript table interfaces with Knex module augmentation for type-safe queries',
  language: 'typescript',
  configSchema,

  generate(ctx) {
    const config = ctx.config ?? {}
    const options: TsTypeOptions = {
      dateType: config.dateType,
      bigintType: config.bigintType,
      nullableStyle: 'null-union',
    }

    const schema = enrichRealm(ctx)
    const lines: string[] = [
      '// Generated by @sqldoc/templates/knex -- DO NOT EDIT',
      '',
      "import type { Knex } from 'knex'",
      '',
    ]

    if (hasJsonTypes(schema)) {
      lines.push(JSON_TYPE_DECLARATION)
      lines.push('')
    }

    // Enums
    for (const e of schema.enums) {
      const values = e.values.map((v) => `'${v}'`).join(' | ')
      lines.push(`export type ${e.pascalName} = ${values}`)
      lines.push('')
    }

    // Composite types (collected from columns)
    const composites = collectCompositeTypes(schema)
    emitCompositeInterfaces(lines, composites, options)

    // Generate per-table interfaces
    const tableEntries: string[] = []

    for (const table of activeTables(schema)) {
      const interfaceName = `${table.pascalName}Table`

      lines.push(`export interface ${interfaceName} {`)

      for (const col of table.columns) {
        const tsType = resolveTsColumnType(col, options)
        lines.push(`  ${col.name}: ${tsType}`)
      }

      lines.push('}')
      lines.push('')

      tableEntries.push(`    '${table.sqlName}': ${interfaceName}`)
    }

    // Views (read-only)
    const viewEntries: string[] = []

    for (const view of schema.views.filter((v) => !v.skipped)) {
      const interfaceName = `${view.pascalName}View`

      lines.push(`/** Read-only (from view) */`)
      lines.push(`export interface ${interfaceName} {`)

      for (const col of view.columns) {
        const tsType = resolveTsColumnType(col, options)
        lines.push(`  ${col.name}: ${tsType}`)
      }

      lines.push('}')
      lines.push('')

      viewEntries.push(`    '${view.sqlName}': ${interfaceName}`)
    }

    // Knex module augmentation for type-safe table map
    lines.push("declare module 'knex/types/tables' {")
    lines.push('  interface Tables {')
    for (const entry of tableEntries) {
      lines.push(entry)
    }
    for (const entry of viewEntries) {
      lines.push(entry)
    }
    lines.push('  }')
    lines.push('}')
    lines.push('')

    // Functions (skip trigger functions)
    for (const fn of schema.functions) {
      const retRaw = fn.returnType?.type?.toLowerCase() ?? ''
      if (retRaw === 'trigger') continue

      const params = inputFunctionParams(fn, options)
        .map((p) => `${p.name}: ${p.type}`)
        .join(', ')

      const retType = resolveFunctionReturnType(fn, schema, options, composites, 'Table')

      lines.push(`export type ${fn.pascalName} = (${params}) => ${retType}`)
      lines.push('')
    }

    return {
      files: [
        {
          path: 'database.ts',
          content: lines.join('\n'),
        },
      ],
    }
  },
})
