# Generated by @sqldoc/templates/ruby-activerecord -- DO NOT EDIT
# frozen_string_literal: true

class Owner < ApplicationRecord
  self.table_name = 'owners'

  has_many :adoptions
  has_many :reviews

  validates :name, presence: true
  validates :phone, length: { minimum: 7, maximum: 20 }
end
