# Generated by @sqldoc/templates/ruby-activerecord -- DO NOT EDIT
# frozen_string_literal: true

class Review < ApplicationRecord
  self.table_name = 'reviews'

  belongs_to :location
  belongs_to :owner
  belongs_to :pet

  validates :body, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
end
