// Generated by @sqldoc/templates/drizzle -- DO NOT EDIT

import { bigint, date, integer, pgSchema, text } from 'drizzle-orm/pg-core'
import { sql } from 'drizzle-orm'

export const dboSchema = pgSchema('dbo')

export const adoption = dboSchema.table('adoptions', {
  id: integer('id').primaryKey().notNull(),
  petId: integer('pet_id').notNull().references(() => pet.id),
  ownerId: integer('owner_id').notNull().references(() => owner.id),
  adoptedAt: text('adopted_at').notNull().default(sql`getdate()`),
  adoptionFee: text('adoption_fee').notNull().default(0),
  updatedBy: text('updated_by'),
})

export const adoptionsauditlog = dboSchema.table('adoptions_audit_log', {
  id: bigint('id', { mode: 'number' }).primaryKey().notNull(),
  tableName: text('table_name').notNull(),
  operation: text('operation').notNull(),
  oldData: text('old_data'),
  newData: text('new_data'),
  changedAt: text('changed_at').notNull().default(sql`getdate()`),
})

export const category = dboSchema.table('categories', {
  id: integer('id').primaryKey().notNull(),
  name: text('name').notNull(),
  description: text('description'),
})

export const legacyinventory = dboSchema.table('legacy_inventory', {
  id: integer('id').primaryKey().notNull(),
  itemName: text('item_name'),
  oldSku: text('old_sku'),
  quantity: integer('quantity').default(0),
})

export const location = dboSchema.table('locations', {
  id: integer('id').primaryKey().notNull(),
  name: text('name').notNull(),
  address: text('address').notNull(),
  city: text('city').notNull(),
  zip: text('zip'),
})

export const medicalrecord = dboSchema.table('medical_records', {
  id: integer('id').primaryKey().notNull(),
  petId: integer('pet_id').notNull().references(() => pet.id),
  visitDate: date('visit_date').notNull().default(sql`CONVERT([date],getdate())`),
  diagnosis: text('diagnosis').notNull(),
  treatment: text('treatment'),
  vetName: text('vet_name'),
})

export const owner = dboSchema.table('owners', {
  id: integer('id').primaryKey().notNull(),
  name: text('name').notNull(),
  email: text('email').notNull(),
  phone: text('phone'),
  createdAt: text('created_at').default(sql`getdate()`),
})

export const pet = dboSchema.table('pets', {
  id: integer('id').primaryKey().notNull(),
  categoryId: integer('category_id').references(() => category.id),
  name: text('name').notNull(),
  sku: text('sku').notNull(),
  price: text('price').notNull().default(0),
  internalNotes: text('internal_notes'),
  status: text('status').notNull().default('available'),
  createdAt: text('created_at').default(sql`getdate()`),
})

export const review = dboSchema.table('reviews', {
  id: integer('id').primaryKey().notNull(),
  petId: integer('pet_id').notNull().references(() => pet.id),
  ownerId: integer('owner_id').notNull().references(() => owner.id),
  rating: integer('rating').notNull(),
  body: text('body'),
  locationId: integer('location_id').references(() => location.id),
  createdAt: text('created_at').default(sql`getdate()`),
})

export const staffauditlog = dboSchema.table('staff_audit_log', {
  id: bigint('id', { mode: 'number' }).primaryKey().notNull(),
  tableName: text('table_name').notNull(),
  operation: text('operation').notNull(),
  oldData: text('old_data'),
  newData: text('new_data'),
  changedAt: text('changed_at').notNull().default(sql`getdate()`),
})
