# Generated by @sqldoc/templates/sqlalchemy -- DO NOT EDIT

from sqlalchemy import BigInteger, Column, Date, Integer, String, ForeignKey
from sqlalchemy.orm import declarative_base

Base = declarative_base()


class Adoption(Base):
    __tablename__ = 'adoptions'

    id = Column(Integer, primary_key=True)
    pet_id = Column(Integer, ForeignKey('pets.id'), nullable=False)
    owner_id = Column(Integer, ForeignKey('owners.id'), nullable=False)
    adopted_at = Column(String, nullable=False)
    adoption_fee = Column(String, nullable=False)
    updated_by = Column(String)


class AdoptionsAuditLog(Base):
    __tablename__ = 'adoptions_audit_log'

    id = Column(BigInteger, primary_key=True)
    table_name = Column(String, nullable=False)
    operation = Column(String, nullable=False)
    old_data = Column(String)
    new_data = Column(String)
    changed_at = Column(String, nullable=False)


class Category(Base):
    __tablename__ = 'categories'

    id = Column(Integer, primary_key=True)
    name = Column(String, nullable=False)
    description = Column(String)


class LegacyInventory(Base):
    __tablename__ = 'legacy_inventory'

    id = Column(Integer, primary_key=True)
    item_name = Column(String)
    old_sku = Column(String)
    quantity = Column(Integer)


class Location(Base):
    __tablename__ = 'locations'

    id = Column(Integer, primary_key=True)
    name = Column(String, nullable=False)
    address = Column(String, nullable=False)
    city = Column(String, nullable=False)
    zip = Column(String)


class MedicalRecord(Base):
    __tablename__ = 'medical_records'

    id = Column(Integer, primary_key=True)
    pet_id = Column(Integer, ForeignKey('pets.id'), nullable=False)
    visit_date = Column(Date, nullable=False)
    diagnosis = Column(String, nullable=False)
    treatment = Column(String)
    vet_name = Column(String)


class Owner(Base):
    __tablename__ = 'owners'

    id = Column(Integer, primary_key=True)
    name = Column(String, nullable=False)
    email = Column(String, nullable=False)
    phone = Column(String)
    created_at = Column(String)


class Pet(Base):
    __tablename__ = 'pets'

    id = Column(Integer, primary_key=True)
    category_id = Column(Integer, ForeignKey('categories.id'))
    name = Column(String, nullable=False)
    sku = Column(String, nullable=False)
    price = Column(String, nullable=False)
    internal_notes = Column(String)
    status = Column(String, nullable=False)
    created_at = Column(String)


class Review(Base):
    __tablename__ = 'reviews'

    id = Column(Integer, primary_key=True)
    pet_id = Column(Integer, ForeignKey('pets.id'), nullable=False)
    owner_id = Column(Integer, ForeignKey('owners.id'), nullable=False)
    rating = Column(Integer, nullable=False)
    body = Column(String)
    location_id = Column(Integer, ForeignKey('locations.id'))
    created_at = Column(String)


class StaffAuditLog(Base):
    __tablename__ = 'staff_audit_log'

    id = Column(BigInteger, primary_key=True)
    table_name = Column(String, nullable=False)
    operation = Column(String, nullable=False)
    old_data = Column(String)
    new_data = Column(String)
    changed_at = Column(String, nullable=False)

