import { defineTemplate } from '@sqldoc/ns-codegen'
import { activeTables, enrichRealm, type TagEntry } from '../helpers/enrich.ts'
import { singularize, singularizeLast, toPascalCase, toScreamingSnake } from '../helpers/naming.ts'
import { pgToActiveRecordType } from '../types/pg-to-ruby.ts'

export default defineTemplate({
  name: 'Ruby ActiveRecord',
  description: 'Generate ActiveRecord model classes with associations and validations from SQL schema',
  language: 'ruby',

  generate(ctx) {
    const schema = enrichRealm(ctx)
    const files: Array<{ path: string; content: string }> = []

    // Enums (shared constants file)
    if (schema.enums.length > 0) {
      const enumBlocks: string[] = []
      for (const e of schema.enums) {
        const moduleName = toPascalCase(e.name)
        const values = e.values.map((v) => `    ${toScreamingSnake(v)} = '${v}'`).join('\n')
        enumBlocks.push(`  module ${moduleName}\n${values}\n  end`)
      }
      const content = `# Generated by @sqldoc/templates/ruby-activerecord -- DO NOT EDIT
# frozen_string_literal: true

module Enums
${enumBlocks.join('\n\n')}
end
`
      files.push({ path: 'enums.rb', content })
    }

    for (const table of activeTables(schema)) {
      const className = toPascalCase(singularizeLast(table.name))
      const lines: string[] = []

      lines.push(`# Generated by @sqldoc/templates/ruby-activerecord -- DO NOT EDIT`)
      lines.push(`# frozen_string_literal: true`)
      lines.push('')
      lines.push(`class ${className} < ApplicationRecord`)
      lines.push(`  self.table_name = '${table.sqlName ?? table.name}'`)

      // Associations: belongs_to
      if (table.belongsTo.length > 0) {
        lines.push('')
        for (const rel of table.belongsTo) {
          const assocName = singularize(rel.foreignTable)
          const foreignKey = rel.column
          // Only add foreign_key if it doesn't follow convention ({assocName}_id)
          if (foreignKey === `${assocName}_id`) {
            lines.push(`  belongs_to :${assocName}`)
          } else {
            lines.push(`  belongs_to :${assocName}, foreign_key: '${foreignKey}'`)
          }
        }
      }

      // Associations: has_many
      if (table.hasMany.length > 0) {
        lines.push('')
        for (const rel of table.hasMany) {
          const assocName = rel.foreignTable
          const foreignKey = rel.foreignColumn
          const expectedFk = `${singularize(table.name)}_id`
          if (foreignKey === expectedFk) {
            lines.push(`  has_many :${assocName}`)
          } else {
            lines.push(`  has_many :${assocName}, foreign_key: '${foreignKey}'`)
          }
        }
      }

      // Enum declarations (columns that are enum type)
      const enumCols = table.columns.filter((c) => c.category === 'enum' && c.enumValues?.length)
      if (enumCols.length > 0) {
        lines.push('')
        for (const col of enumCols) {
          const values = col.enumValues!.map((v) => `${v}: '${v}'`).join(', ')
          lines.push(`  enum :${col.name}, { ${values} }`)
        }
      }

      // Attribute declarations for non-standard types
      const attrCols = table.columns.filter((c) => {
        const arType = pgToActiveRecordType(c.pgType, c.category)
        return arType === 'json' || arType === 'decimal' || arType === 'binary' || arType === 'array'
      })
      if (attrCols.length > 0) {
        lines.push('')
        for (const col of attrCols) {
          const arType = pgToActiveRecordType(col.pgType, col.category)
          lines.push(`  attribute :${col.name}, :${arType}`)
        }
      }

      // Validations from @validate tags
      const validations = buildValidations(table.columns)
      if (validations.length > 0) {
        lines.push('')
        for (const v of validations) {
          lines.push(`  ${v}`)
        }
      }

      lines.push('end')
      lines.push('')

      const fileName = singularizeLast(table.name).replace(/\./g, '_')
      files.push({ path: `${fileName}.rb`, content: lines.join('\n') })
    }

    // Views (read-only models)
    for (const view of schema.views.filter((v) => !v.skipped)) {
      const className = toPascalCase(singularizeLast(view.name))
      const lines: string[] = []

      lines.push(`# Generated by @sqldoc/templates/ruby-activerecord -- DO NOT EDIT`)
      lines.push(`# frozen_string_literal: true`)
      lines.push('')
      lines.push(`# Read-only (from view)`)
      lines.push(`class ${className} < ApplicationRecord`)
      lines.push(`  self.table_name = '${view.name}'`)
      lines.push('')
      lines.push('  def readonly?')
      lines.push('    true')
      lines.push('  end')
      lines.push('end')
      lines.push('')

      const fileName = singularizeLast(view.name).replace(/\./g, '_')
      files.push({ path: `${fileName}.rb`, content: lines.join('\n') })
    }

    return { files }
  },
})

interface ColumnWithTags {
  name: string
  tags: TagEntry[]
  nullable: boolean
}

function buildValidations(columns: ColumnWithTags[]): string[] {
  const validations: string[] = []

  for (const col of columns) {
    const validateTags = col.tags.filter((t) => t.namespace === 'validate')
    if (validateTags.length === 0) continue

    for (const tag of validateTags) {
      switch (tag.tag) {
        case 'notEmpty':
          validations.push(`validates :${col.name}, presence: true`)
          break
        case 'length': {
          const args = tag.args as Record<string, unknown>
          if (args && typeof args === 'object' && !Array.isArray(args)) {
            const parts: string[] = []
            if ('min' in args) parts.push(`minimum: ${args.min}`)
            if ('max' in args) parts.push(`maximum: ${args.max}`)
            if (parts.length > 0) {
              validations.push(`validates :${col.name}, length: { ${parts.join(', ')} }`)
            }
          }
          break
        }
        case 'range': {
          const args = tag.args as Record<string, unknown>
          if (args && typeof args === 'object' && !Array.isArray(args)) {
            const parts: string[] = []
            if ('min' in args) parts.push(`greater_than_or_equal_to: ${args.min}`)
            if ('max' in args) parts.push(`less_than_or_equal_to: ${args.max}`)
            if (parts.length > 0) {
              validations.push(`validates :${col.name}, numericality: { ${parts.join(', ')} }`)
            }
          }
          break
        }
        case 'pattern': {
          const args = tag.args
          if (Array.isArray(args) && args.length > 0) {
            validations.push(`validates :${col.name}, format: { with: /${args[0]}/ }`)
          }
          break
        }
      }
    }
  }

  return validations
}
