import { defineTemplate } from '@sqldoc/ns-codegen'
import { activeTables, enrichRealm } from '../helpers/enrich.ts'
import { toCamelCase, toPascalCase } from '../helpers/naming.ts'
import { JSON_TYPE_DECLARATION, pgToTs, type TsTypeOptions } from '../types/pg-to-ts.ts'

export const configSchema = {
  dateType: {
    type: 'enum',
    values: ['Date', 'temporal', 'dayjs', 'luxon', 'string'],
    description: 'How to represent date/time types',
  },
  nullableStyle: {
    type: 'enum',
    values: ['optional', 'null-union'],
    description: 'Use optional properties (?) or explicit null unions (| null)',
  },
  bigintType: {
    type: 'enum',
    values: ['number', 'bigint', 'string'],
    description: 'How to represent bigint/bigserial columns',
  },
} as const

export default defineTemplate({
  name: 'TypeScript Interfaces',
  description: 'Generate TypeScript interface definitions from SQL schema',
  language: 'typescript',
  configSchema,

  generate(ctx) {
    const config = ctx.config ?? {}
    const options: TsTypeOptions = {
      dateType: config.dateType,
      nullableStyle: config.nullableStyle,
      bigintType: config.bigintType,
    }

    const schema = enrichRealm(ctx)
    const lines: string[] = ['// Generated by @sqldoc/templates/typescript -- DO NOT EDIT', '']

    // Emit Json type if any json/jsonb columns exist
    const allCols = [...schema.tables.flatMap((t) => t.columns), ...schema.views.flatMap((v) => v.columns)]
    if (allCols.some((c) => c.category === 'json' || c.pgType === 'json' || c.pgType === 'jsonb')) {
      lines.push(JSON_TYPE_DECLARATION)
      lines.push('')
    }

    // When using Temporal API date types, emit a global declaration so the code typechecks
    // even without a full Temporal polyfill type package installed.
    if (options.dateType === 'temporal') {
      lines.push('declare global {')
      lines.push('  namespace Temporal {')
      lines.push('    interface Instant { toString(): string }')
      lines.push('    interface PlainDate { toString(): string }')
      lines.push('    interface PlainTime { toString(): string }')
      lines.push('    interface PlainDateTime { toString(): string }')
      lines.push('    interface ZonedDateTime { toString(): string }')
      lines.push('    interface Duration { toString(): string }')
      lines.push('  }')
      lines.push('}')
      lines.push('')
    }

    // Enums
    for (const e of schema.enums) {
      lines.push(`export type ${e.pascalName} = ${e.values.map((v) => `'${v}'`).join(' | ')}`)
      lines.push('')
    }

    // Composite types (collected from columns)
    const composites = new Map<string, Array<{ name: string; type: string }>>()
    for (const table of schema.tables) {
      for (const col of table.columns) {
        if (col.category === 'composite' && col.compositeFields?.length && !composites.has(col.pgType)) {
          composites.set(col.pgType, col.compositeFields)
        }
      }
    }
    for (const fn of schema.functions) {
      if (fn.returnType?.category === 'composite' && fn.returnType.compositeFields?.length) {
        const typeName = fn.returnType.type.replace(/^setof\s+/i, '')
        if (!composites.has(typeName)) {
          composites.set(typeName, fn.returnType.compositeFields)
        }
      }
    }
    for (const [name, fields] of composites) {
      const typeName =
        name.charAt(0).toUpperCase() + name.slice(1).replace(/_([a-z])/g, (_: string, c: string) => c.toUpperCase())
      lines.push(`export interface ${typeName} {`)
      for (const f of fields) {
        lines.push(`  ${toCamelCase(f.name)}: ${pgToTs(f.type, false, options)}`)
      }
      lines.push('}')
      lines.push('')
    }

    // Tables
    for (const table of activeTables(schema)) {
      lines.push(`export interface ${table.pascalName} {`)
      for (const col of table.columns) {
        const tsType = resolveType(col, config, options)
        const propName = toCamelCase(col.name)
        if (col.nullable && config.nullableStyle !== 'null-union') {
          lines.push(`  ${propName}?: ${tsType}`)
        } else {
          lines.push(`  ${propName}: ${tsType}`)
        }
      }
      lines.push('}')
      lines.push('')
    }

    // Views (read-only)
    for (const view of schema.views.filter((v) => !v.skipped)) {
      const hasUnnamed = view.columns.some((c) => !c.name)
      if (hasUnnamed) {
        // Views with unnamed columns (e.g. SELECT 1) → tuple type
        const types = view.columns.map((col) => resolveType(col, config, options))
        const tupleType = types.length === 1 ? types[0] : `[${types.join(', ')}]`
        lines.push(`/** Read-only (from view) */`)
        lines.push(`export type ${view.pascalName} = ${tupleType}`)
        lines.push('')
      } else {
        lines.push(`/** Read-only (from view) */`)
        lines.push(`export interface ${view.pascalName} {`)
        for (const col of view.columns) {
          const tsType = resolveType(col, config, options)
          const propName = toCamelCase(col.name)
          if (col.nullable && config.nullableStyle !== 'null-union') {
            lines.push(`  ${propName}?: ${tsType}`)
          } else {
            lines.push(`  ${propName}: ${tsType}`)
          }
        }
        lines.push('}')
        lines.push('')
      }
    }

    // Functions (skip trigger functions — they're not user-callable)
    for (const fn of schema.functions) {
      const retRaw = fn.returnType?.type?.toLowerCase() ?? ''
      if (retRaw === 'trigger') continue

      const filteredArgs = fn.args.filter((a) => !a.name?.startsWith('_') && (a as any).mode !== 'OUT')
      const usedNames = new Set<string>()
      const params = filteredArgs
        .map((a, i) => {
          const argType = pgToTs(a.type, false, options, a.category as any)
          let argName = a.name ? toCamelCase(a.name) : `arg${i + 1}`
          // Deduplicate: if name already used, append index
          if (usedNames.has(argName)) argName = `${argName}${i + 1}`
          usedNames.add(argName)
          return `${argName}: ${argType}`
        })
        .join(', ')

      let retType: string
      if (retRaw.startsWith('setof ')) {
        // RETURNS SETOF tablename → Table[] or CompositeType[]
        const tableName = retRaw.replace('setof ', '')
        const table = schema.tables.find((t) => t.name === tableName || t.sqlName === tableName)
        retType = table
          ? `${table.pascalName}[]`
          : composites.has(tableName)
            ? `${toPascalCase(tableName)}[]`
            : `${pgToTs(tableName, false, options)}[]`
      } else if (fn.returnType) {
        retType = pgToTs(fn.returnType.type, false, options, fn.returnType.category as any)
      } else {
        // Procedures (no formal return type) return result sets — use unknown[]
        retType = 'unknown[]'
      }

      lines.push(`export type ${fn.pascalName} = (${params}) => ${retType}`)
      lines.push('')
    }

    return {
      files: [
        {
          path: 'models.ts',
          content: lines.join('\n'),
        },
      ],
    }

    function resolveType(col: any, config: any, options: TsTypeOptions): string {
      if (col.typeOverride) return col.typeOverride
      const toPascal = (s: string) =>
        s.charAt(0).toUpperCase() + s.slice(1).replace(/_([a-z])/g, (_: string, c: string) => c.toUpperCase())
      if (col.category === 'enum' && col.enumValues?.length) {
        const enumType = toPascal(col.pgType)
        return col.nullable && config.nullableStyle === 'null-union' ? `${enumType} | null` : enumType
      }
      if (col.category === 'composite' && col.compositeFields?.length) {
        const compositeType = toPascal(col.pgType)
        return col.nullable && config.nullableStyle === 'null-union' ? `${compositeType} | null` : compositeType
      }
      return pgToTs(col.pgType, col.nullable && config.nullableStyle === 'null-union', options, col.category)
    }
  },
})
