import { defineTemplate } from '@sqldoc/ns-codegen'
import { activeTables, enrichRealm } from '../helpers/enrich.ts'
import { toCamelCase } from '../helpers/naming.ts'
import {
  collectCompositeTypes,
  emitCompositeInterfaces,
  hasJsonTypes,
  inputFunctionParams,
  resolveFunctionReturnType,
  resolveTsColumnType,
} from '../helpers/typescript.ts'
import { JSON_TYPE_DECLARATION, type TsTypeOptions } from '../types/pg-to-ts.ts'

export const configSchema = {
  dateType: {
    type: 'enum',
    values: ['Date', 'temporal', 'dayjs', 'luxon', 'string'],
    description: 'How to represent date/time types',
  },
  nullableStyle: {
    type: 'enum',
    values: ['optional', 'null-union'],
    description: 'Use optional properties (?) or explicit null unions (| null)',
  },
  bigintType: {
    type: 'enum',
    values: ['number', 'bigint', 'string'],
    description: 'How to represent bigint/bigserial columns',
  },
} as const

export default defineTemplate({
  name: 'TypeScript Interfaces',
  description: 'Generate TypeScript interface definitions from SQL schema',
  language: 'typescript',
  configSchema,

  generate(ctx) {
    const config = ctx.config ?? {}
    const options: TsTypeOptions = {
      dateType: config.dateType,
      nullableStyle: config.nullableStyle,
      bigintType: config.bigintType,
    }

    const schema = enrichRealm(ctx)
    const lines: string[] = ['// Generated by @sqldoc/templates/typescript -- DO NOT EDIT', '']

    // Emit Json type if any json/jsonb columns exist
    if (hasJsonTypes(schema)) {
      lines.push(JSON_TYPE_DECLARATION)
      lines.push('')
    }

    // When using Temporal API date types, emit a global declaration so the code typechecks
    // even without a full Temporal polyfill type package installed.
    if (options.dateType === 'temporal') {
      lines.push('declare global {')
      lines.push('  namespace Temporal {')
      lines.push('    interface Instant { toString(): string }')
      lines.push('    interface PlainDate { toString(): string }')
      lines.push('    interface PlainTime { toString(): string }')
      lines.push('    interface PlainDateTime { toString(): string }')
      lines.push('    interface ZonedDateTime { toString(): string }')
      lines.push('    interface Duration { toString(): string }')
      lines.push('  }')
      lines.push('}')
      lines.push('')
    }

    // Enums
    for (const e of schema.enums) {
      lines.push(`export type ${e.pascalName} = ${e.values.map((v) => `'${v}'`).join(' | ')}`)
      lines.push('')
    }

    // Composite types (collected from columns)
    const composites = collectCompositeTypes(schema)
    emitCompositeInterfaces(lines, composites, options)

    // Tables
    for (const table of activeTables(schema)) {
      lines.push(`export interface ${table.pascalName} {`)
      for (const col of table.columns) {
        const tsType = resolveTsColumnType(col, options, config.nullableStyle)
        const propName = toCamelCase(col.name)
        if (col.nullable && config.nullableStyle !== 'null-union') {
          lines.push(`  ${propName}?: ${tsType}`)
        } else {
          lines.push(`  ${propName}: ${tsType}`)
        }
      }
      lines.push('}')
      lines.push('')
    }

    // Views (read-only)
    for (const view of schema.views.filter((v) => !v.skipped)) {
      const hasUnnamed = view.columns.some((c) => !c.name)
      if (hasUnnamed) {
        // Views with unnamed columns (e.g. SELECT 1) → tuple type
        const types = view.columns.map((col) => resolveTsColumnType(col, options, config.nullableStyle))
        const tupleType = types.length === 1 ? types[0] : `[${types.join(', ')}]`
        lines.push(`/** Read-only (from view) */`)
        lines.push(`export type ${view.pascalName} = ${tupleType}`)
        lines.push('')
      } else {
        lines.push(`/** Read-only (from view) */`)
        lines.push(`export interface ${view.pascalName} {`)
        for (const col of view.columns) {
          const tsType = resolveTsColumnType(col, options, config.nullableStyle)
          const propName = toCamelCase(col.name)
          if (col.nullable && config.nullableStyle !== 'null-union') {
            lines.push(`  ${propName}?: ${tsType}`)
          } else {
            lines.push(`  ${propName}: ${tsType}`)
          }
        }
        lines.push('}')
        lines.push('')
      }
    }

    // Functions (skip trigger functions — they're not user-callable)
    for (const fn of schema.functions) {
      const retRaw = fn.returnType?.type?.toLowerCase() ?? ''
      if (retRaw === 'trigger') continue

      const params = inputFunctionParams(fn, options)
        .map((p) => `${p.name}: ${p.type}`)
        .join(', ')
      const retType = resolveFunctionReturnType(fn, schema, options, composites)

      lines.push(`export type ${fn.pascalName} = (${params}) => ${retType}`)
      lines.push('')
    }

    return {
      files: [
        {
          path: 'models.ts',
          content: lines.join('\n'),
        },
      ],
    }
  },
})
