<?php
// Generated by @sqldoc/templates/php-eloquent -- DO NOT EDIT

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * AdoptionsAuditLog
 *
 * @property int $id
 * @property string $table_name
 * @property string $operation
 * @property ?string $old_data
 * @property ?string $new_data
 * @property string $changed_at
 */
class AdoptionsAuditLog extends Model
{
    protected $table = 'adoptions_audit_log';

    public $timestamps = false;

    protected $fillable = [
        'table_name',
        'operation',
        'old_data',
        'new_data',
        'changed_at',
    ];

    protected $casts = [
        'changed_at' => 'datetime',
    ];

}
