<?php
// Generated by @sqldoc/templates/php-eloquent -- DO NOT EDIT

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * Pet
 *
 * @property int $id
 * @property ?int $category_id
 * @property string $name
 * @property string $sku
 * @property float $price
 * @property ?string $internal_notes
 * @property string $status
 * @property ?string $created_at
 */
class Pet extends Model
{
    protected $table = 'pets';

    public $timestamps = false;

    protected $fillable = [
        'category_id',
        'name',
        'sku',
        'price',
        'internal_notes',
        'status',
        'created_at',
    ];

    protected $casts = [
        'category_id' => 'integer',
        'price' => 'decimal:2',
    ];

    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class);
    }

    public function adoptions(): HasMany
    {
        return $this->hasMany(Adoption::class);
    }

    public function medicalRecords(): HasMany
    {
        return $this->hasMany(MedicalRecord::class);
    }

    public function reviews(): HasMany
    {
        return $this->hasMany(Review::class);
    }

}
