<?php
// Generated by @sqldoc/templates/php-eloquent -- DO NOT EDIT

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * Review
 *
 * @property int $id
 * @property int $pet_id
 * @property int $owner_id
 * @property int $rating
 * @property ?string $body
 * @property ?int $location_id
 * @property ?string $created_at
 */
class Review extends Model
{
    protected $table = 'reviews';

    public $timestamps = false;

    protected $fillable = [
        'pet_id',
        'owner_id',
        'rating',
        'body',
        'location_id',
        'created_at',
    ];

    protected $casts = [
        'pet_id' => 'integer',
        'owner_id' => 'integer',
        'rating' => 'integer',
        'location_id' => 'integer',
    ];

    public function location(): BelongsTo
    {
        return $this->belongsTo(Location::class);
    }

    public function owner(): BelongsTo
    {
        return $this->belongsTo(Owner::class);
    }

    public function pet(): BelongsTo
    {
        return $this->belongsTo(Pet::class);
    }

}
