# Generated by @sqldoc/templates/sqlalchemy -- DO NOT EDIT

from sqlalchemy import BigInteger, Column, Date, DateTime, Integer, JSON, Numeric, String, Text, ForeignKey
from sqlalchemy.orm import declarative_base

Base = declarative_base()


class Adoption(Base):
    __tablename__ = 'adoptions'

    id = Column(Integer, primary_key=True)
    pet_id = Column(Integer, ForeignKey('pets.id'), nullable=False)
    owner_id = Column(Integer, ForeignKey('owners.id'), nullable=False)
    adopted_at = Column(DateTime, nullable=False)
    adoption_fee = Column(Numeric(10, 2), nullable=False)


class AdoptionsAuditLog(Base):
    __tablename__ = 'adoptions_audit_log'

    id = Column(BigInteger, primary_key=True)
    table_name = Column(Text, nullable=False)
    operation = Column(Text, nullable=False)
    old_data = Column(JSON)
    new_data = Column(JSON)
    changed_at = Column(DateTime, nullable=False)


class Category(Base):
    __tablename__ = 'categories'

    id = Column(Integer, primary_key=True)
    name = Column(String(100), nullable=False)
    description = Column(Text)


class LegacyInventory(Base):
    __tablename__ = 'legacy_inventory'

    id = Column(Integer, primary_key=True)
    item_name = Column(String(200))
    old_sku = Column(String(50))
    quantity = Column(Integer)


class Location(Base):
    __tablename__ = 'locations'

    id = Column(Integer, primary_key=True)
    name = Column(String(200), nullable=False)
    address = Column(Text, nullable=False)
    city = Column(String(100), nullable=False)
    zip = Column(String(20))


class MedicalRecord(Base):
    __tablename__ = 'medical_records'

    id = Column(Integer, primary_key=True)
    pet_id = Column(Integer, ForeignKey('pets.id'), nullable=False)
    visit_date = Column(Date, nullable=False)
    diagnosis = Column(Text, nullable=False)
    treatment = Column(Text)
    vet_name = Column(String(150))


class Owner(Base):
    __tablename__ = 'owners'

    id = Column(Integer, primary_key=True)
    name = Column(String(150), nullable=False)
    email = Column(String(255), nullable=False)
    phone = Column(String(20))
    created_at = Column(DateTime)


class Pet(Base):
    __tablename__ = 'pets'

    id = Column(Integer, primary_key=True)
    category_id = Column(Integer, ForeignKey('categories.id'))
    name = Column(String(100), nullable=False)
    sku = Column(String(20), nullable=False)
    price = Column(Numeric(10, 2), nullable=False)
    internal_notes = Column(Text)
    status = Column(String(20), nullable=False)
    created_at = Column(DateTime)


class Review(Base):
    __tablename__ = 'reviews'

    id = Column(Integer, primary_key=True)
    pet_id = Column(Integer, nullable=False)
    owner_id = Column(Integer, nullable=False)
    rating = Column(Integer, nullable=False)
    body = Column(Text)
    location_id = Column(Integer, ForeignKey('locations.id'))
    created_at = Column(DateTime)


class StaffAuditLog(Base):
    __tablename__ = 'staff_audit_log'

    id = Column(BigInteger, primary_key=True)
    table_name = Column(Text, nullable=False)
    operation = Column(Text, nullable=False)
    old_data = Column(JSON)
    new_data = Column(JSON)
    changed_at = Column(DateTime, nullable=False)

