import { defineTemplate } from '@sqldoc/ns-codegen'
import { activeTables, enrichRealm } from '../helpers/enrich.ts'
import { toPascalCase } from '../helpers/naming.ts'
import { pgToGo } from '../types/pg-to-go.ts'

export default defineTemplate({
  name: 'GORM Models',
  description: 'Generate Go structs with GORM struct tags from SQL schema',
  language: 'go',

  generate(ctx) {
    const schema = enrichRealm(ctx)
    const allImports = new Set<string>()
    const structBlocks: string[] = []

    // Enums
    for (const e of schema.enums) {
      const typeName = toPascalCase(e.name)
      structBlocks.push(`type ${typeName} string`)
      structBlocks.push('')
      const constLines = e.values.map((v) => {
        const constName = `${typeName}${toPascalCase(v)}`
        return `\t${constName} ${typeName} = "${v}"`
      })
      structBlocks.push(`const (\n${constLines.join('\n')}\n)`)
    }

    // Composite types (collected from columns)
    const composites = new Map<string, Array<{ name: string; type: string }>>()
    for (const table of schema.tables) {
      for (const col of table.columns) {
        if (col.category === 'composite' && col.compositeFields?.length && !composites.has(col.pgType)) {
          composites.set(col.pgType, col.compositeFields)
        }
      }
    }
    for (const view of schema.views) {
      for (const col of view.columns) {
        if (col.category === 'composite' && col.compositeFields?.length && !composites.has(col.pgType)) {
          composites.set(col.pgType, col.compositeFields)
        }
      }
    }
    for (const [name, fields] of composites) {
      const typeName = toPascalCase(name)
      const fieldLines = fields.map((f) => {
        const mapped = pgToGo(f.type, false)
        for (const imp of mapped.imports) allImports.add(imp)
        const jsonTag = `json:"${f.name}"`
        return `\t${toPascalCase(f.name)} ${mapped.type} \`${jsonTag}\``
      })
      structBlocks.push(`type ${typeName} struct {\n${fieldLines.join('\n')}\n}`)
    }

    // Helper to resolve Go type for a column
    function resolveGoType(col: any): string {
      if (col.typeOverride) return col.typeOverride
      if (col.category === 'enum' && col.enumValues?.length) {
        return col.nullable ? `*${toPascalCase(col.pgType)}` : toPascalCase(col.pgType)
      }
      if (col.category === 'composite' && col.compositeFields?.length) {
        return col.nullable ? `*${toPascalCase(col.pgType)}` : toPascalCase(col.pgType)
      }
      const mapped = pgToGo(col.pgType, col.nullable, col.category)
      for (const imp of mapped.imports) allImports.add(imp)
      return mapped.type
    }

    for (const table of activeTables(schema)) {
      const fields: string[] = []

      for (const col of table.columns) {
        const goType = resolveGoType(col)

        // Build GORM tag parts
        const gormParts: string[] = []
        if (col.isPrimaryKey) gormParts.push('primaryKey')
        gormParts.push(`type:${col.pgType}`)
        if (!col.nullable) gormParts.push('not null')
        if (col.isSerial) gormParts.push('autoIncrement')
        if (col.defaultValue) gormParts.push(`default:${col.defaultValue}`)
        if (col.foreignKey) {
          gormParts.push(`foreignKey:${col.foreignKey.column}`)
        }

        const gormTag = `gorm:"${gormParts.join(';')}"`
        const jsonTag = `json:"${col.name},omitempty"`
        const tag = `\`${gormTag} ${jsonTag}\``

        fields.push(`\t${col.pascalName} ${goType} ${tag}`)
      }

      structBlocks.push(`type ${table.pascalName} struct {\n${fields.join('\n')}\n}`)
    }

    // Views (read-only)
    for (const view of schema.views.filter((v) => !v.skipped)) {
      const fields: string[] = []

      for (const col of view.columns) {
        const goType = resolveGoType(col)

        const gormTag = `gorm:"type:${col.pgType}"`
        const jsonTag = `json:"${col.name},omitempty"`
        const tag = `\`${gormTag} ${jsonTag}\``

        fields.push(`\t${col.pascalName} ${goType} ${tag}`)
      }

      structBlocks.push(
        `// ${view.pascalName} is read-only (from view)\ntype ${view.pascalName} struct {\n${fields.join('\n')}\n}`,
      )
    }

    let importBlock = ''
    if (allImports.size > 0) {
      const sorted = [...allImports].sort()
      if (sorted.length === 1) {
        importBlock = `import "${sorted[0]}"\n\n`
      } else {
        importBlock = `import (\n${sorted.map((i) => `\t"${i}"`).join('\n')}\n)\n\n`
      }
    }

    const content = `// Generated by @sqldoc/templates/gorm -- DO NOT EDIT
package models

${importBlock}${structBlocks.join('\n\n')}\n`

    return {
      files: [{ path: 'models.go', content }],
    }
  },
})
