# Generated by @sqldoc/templates/ruby-activerecord -- DO NOT EDIT
# frozen_string_literal: true

class Adoption < ApplicationRecord
  self.table_name = 'adoptions'

  belongs_to :owner
  belongs_to :pet

  attribute :adoption_fee, :decimal
end
