# Generated by @sqldoc/templates/ruby-activerecord -- DO NOT EDIT
# frozen_string_literal: true

class Owner < ApplicationRecord
  self.table_name = 'owners'

  has_many :adoptions

  validates :name, presence: true
  validates :email, format: { with: /^[^@]+@[^@]+\.[^@]+$/ }
  validates :phone, length: { minimum: 7, maximum: 20 }
end
