# Generated by @sqldoc/templates/ruby-activerecord -- DO NOT EDIT
# frozen_string_literal: true

class Pet < ApplicationRecord
  self.table_name = 'pets'

  belongs_to :category

  has_many :adoptions
  has_many :medical_records

  attribute :price, :decimal

  validates :name, presence: true
  validates :sku, format: { with: /^[A-Z]{3}-[0-9]{4}$/ }
  validates :price, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 99999 }
end
