# Generated by @sqldoc/templates/ruby-activerecord -- DO NOT EDIT
# frozen_string_literal: true

# Read-only (from view)
class ActiveUser < ApplicationRecord
  self.table_name = 'active_users'

  def readonly?
    true
  end
end
