# Generated by @sqldoc/templates/ruby-activerecord -- DO NOT EDIT
# frozen_string_literal: true

class Comment < ApplicationRecord
  self.table_name = 'comments'

  belongs_to :comment, foreign_key: 'parent_id'
  belongs_to :post
  belongs_to :user

  has_many :comments, foreign_key: 'parent_id'
  has_many :post_tags, foreign_key: 'tag_id'
end
