# Generated by @sqldoc/templates/ruby-activerecord -- DO NOT EDIT
# frozen_string_literal: true

class PostTag < ApplicationRecord
  self.table_name = 'post_tags'

  belongs_to :post
  belongs_to :comment, foreign_key: 'tag_id'
end
