# Generated by @sqldoc/templates/ruby-activerecord -- DO NOT EDIT
# frozen_string_literal: true

class Post < ApplicationRecord
  self.table_name = 'content.posts'

  belongs_to :user

  has_many :comments
  has_many :post_tags
end
