# Generated by @sqldoc/templates/ruby-activerecord -- DO NOT EDIT
# frozen_string_literal: true

class User < ApplicationRecord
  self.table_name = 'users'

  has_many :posts
  has_many :comments

  attribute :metadata, :json
  attribute :tags, :array
  attribute :avatar, :binary
  attribute :balance, :decimal

  validates :email, format: { with: Regexp.new(".+@.+\\..+") }
  validates :age, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 120 }
end
