import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, describe, expect, it } from '@sqldoc/test-utils'
import { generateConfigTypes } from '../generate-config-types.ts'

describe('generateConfigTypes', () => {
  const tempDirs: string[] = []

  function makeTempDir(): string {
    const dir = mkdtempSync(join(tmpdir(), 'sqldoc-config-types-test-'))
    tempDirs.push(dir)
    return dir
  }

  afterEach(() => {
    for (const dir of tempDirs) {
      rmSync(dir, { recursive: true, force: true })
    }
    tempDirs.length = 0
  })

  it('does nothing when node_modules/@sqldoc does not exist', () => {
    const sqldocDir = makeTempDir()
    generateConfigTypes(sqldocDir)
    expect(existsSync(join(sqldocDir, 'config.d.ts'))).toBe(false)
  })

  it('generates config.d.ts with base fields when no ns-* packages', () => {
    const sqldocDir = makeTempDir()
    mkdirSync(join(sqldocDir, 'node_modules', '@sqldoc'), { recursive: true })

    generateConfigTypes(sqldocDir)

    const content = readFileSync(join(sqldocDir, 'config.d.ts'), 'utf-8')
    expect(content).toContain('Auto-generated by sqldoc')
    expect(content).toContain('interface ProjectConfig extends BaseProjectConfig')
    expect(content).toContain('export type SqldocConfig = ProjectConfig | ProjectConfig[]')
  })

  it('detects ns-* packages and adds namespace fields', () => {
    const sqldocDir = makeTempDir()
    const nsDir = join(sqldocDir, 'node_modules', '@sqldoc', 'ns-audit')
    mkdirSync(nsDir, { recursive: true })
    writeFileSync(join(nsDir, 'package.json'), JSON.stringify({ name: '@sqldoc/ns-audit' }))

    generateConfigTypes(sqldocDir)

    const content = readFileSync(join(sqldocDir, 'config.d.ts'), 'utf-8')
    expect(content).toContain('namespaces?:')
    expect(content).toContain('audit?: Record<string, unknown>')
  })

  it('picks up exported Config types from namespace source', () => {
    const sqldocDir = makeTempDir()
    const nsDir = join(sqldocDir, 'node_modules', '@sqldoc', 'ns-docs')
    const srcDir = join(nsDir, 'src')
    mkdirSync(srcDir, { recursive: true })
    writeFileSync(join(nsDir, 'package.json'), JSON.stringify({ name: '@sqldoc/ns-docs' }))
    writeFileSync(
      join(srcDir, 'index.ts'),
      `
export default plugin
export type { DocsConfig }
`,
    )

    generateConfigTypes(sqldocDir)

    const content = readFileSync(join(sqldocDir, 'config.d.ts'), 'utf-8')
    expect(content).toContain("import type { DocsConfig } from '@sqldoc/ns-docs'")
    expect(content).toContain('docs?: Partial<DocsConfig>')
  })

  it('handles multiple namespace packages sorted alphabetically', () => {
    const sqldocDir = makeTempDir()
    const sqldocNm = join(sqldocDir, 'node_modules', '@sqldoc')

    // Create ns-validate (no config type)
    const validateDir = join(sqldocNm, 'ns-validate')
    mkdirSync(validateDir, { recursive: true })
    writeFileSync(join(validateDir, 'package.json'), JSON.stringify({ name: '@sqldoc/ns-validate' }))

    // Create ns-codegen (with config type)
    const codegenDir = join(sqldocNm, 'ns-codegen')
    const codegenSrc = join(codegenDir, 'src')
    mkdirSync(codegenSrc, { recursive: true })
    writeFileSync(join(codegenDir, 'package.json'), JSON.stringify({ name: '@sqldoc/ns-codegen' }))
    writeFileSync(join(codegenSrc, 'index.ts'), `export type { CodegenConfig } from './types'`)

    generateConfigTypes(sqldocDir)

    const content = readFileSync(join(sqldocDir, 'config.d.ts'), 'utf-8')
    // codegen comes before validate alphabetically
    expect(content).toContain("import type { CodegenConfig } from '@sqldoc/ns-codegen'")
    expect(content).toContain('codegen?: Partial<CodegenConfig>')
    expect(content).toContain('validate?: Record<string, unknown>')

    // codegen should appear before validate in the file
    const codegenIdx = content.indexOf('codegen?:')
    const validateIdx = content.indexOf('validate?:')
    expect(codegenIdx < validateIdx).toBeTruthy()
  })

  it('skips non-ns packages like cli and templates', () => {
    const sqldocDir = makeTempDir()
    const sqldocNm = join(sqldocDir, 'node_modules', '@sqldoc')

    mkdirSync(join(sqldocNm, 'cli'), { recursive: true })
    writeFileSync(join(sqldocNm, 'cli', 'package.json'), JSON.stringify({ name: '@sqldoc/cli' }))

    mkdirSync(join(sqldocNm, 'templates'), { recursive: true })
    writeFileSync(join(sqldocNm, 'templates', 'package.json'), JSON.stringify({ name: '@sqldoc/templates' }))

    generateConfigTypes(sqldocDir)

    const content = readFileSync(join(sqldocDir, 'config.d.ts'), 'utf-8')
    expect(content).not.toContain('cli')
    expect(content).not.toContain('templates')
  })
})
