import { defineTemplate } from '@sqldoc/ns-codegen'
import { activeTables, type EnrichedColumn, enrichRealm } from '../helpers/enrich.ts'
import { toPascalCase } from '../helpers/naming.ts'

const PG_TO_XSD: Record<string, string> = {
  smallint: 'xs:short',
  int2: 'xs:short',
  integer: 'xs:int',
  int: 'xs:int',
  int4: 'xs:int',
  bigint: 'xs:long',
  int8: 'xs:long',
  serial: 'xs:int',
  serial4: 'xs:int',
  bigserial: 'xs:long',
  serial8: 'xs:long',
  smallserial: 'xs:short',
  serial2: 'xs:short',
  real: 'xs:float',
  float4: 'xs:float',
  'double precision': 'xs:double',
  float8: 'xs:double',
  numeric: 'xs:decimal',
  decimal: 'xs:decimal',
  money: 'xs:decimal',
  text: 'xs:string',
  varchar: 'xs:string',
  'character varying': 'xs:string',
  char: 'xs:string',
  character: 'xs:string',
  name: 'xs:string',
  citext: 'xs:string',
  boolean: 'xs:boolean',
  bool: 'xs:boolean',
  timestamp: 'xs:dateTime',
  'timestamp without time zone': 'xs:dateTime',
  timestamptz: 'xs:dateTime',
  'timestamp with time zone': 'xs:dateTime',
  date: 'xs:date',
  time: 'xs:time',
  'time without time zone': 'xs:time',
  timetz: 'xs:time',
  'time with time zone': 'xs:time',
  interval: 'xs:duration',
  bytea: 'xs:base64Binary',
  json: 'xs:string',
  jsonb: 'xs:string',
  uuid: 'xs:string',
  inet: 'xs:string',
  xml: 'xs:string',
}

function pgToXsd(pgType: string): string {
  const base = pgType
    .toLowerCase()
    .replace(/\(\d+(?:,\s*\d+)?\)/, '')
    .trim()
  if (base.endsWith('[]') || base.startsWith('_')) return 'xs:string'
  return PG_TO_XSD[base] ?? 'xs:string'
}

function buildRestrictions(col: EnrichedColumn): string[] {
  const restrictions: string[] = []
  for (const t of col.tags) {
    if (t.namespace !== 'validate') continue
    if (t.tag === 'notEmpty') restrictions.push('        <xs:minLength value="1"/>')
    else if (t.tag === 'length') {
      const args = t.args as Record<string, unknown>
      if (args.min !== undefined) restrictions.push(`        <xs:minLength value="${args.min}"/>`)
      if (args.max !== undefined) restrictions.push(`        <xs:maxLength value="${args.max}"/>`)
    } else if (t.tag === 'range') {
      const args = t.args as Record<string, unknown>
      if (args.min !== undefined) restrictions.push(`        <xs:minInclusive value="${args.min}"/>`)
      if (args.max !== undefined) restrictions.push(`        <xs:maxInclusive value="${args.max}"/>`)
    } else if (t.tag === 'pattern') {
      const pattern = Array.isArray(t.args) ? t.args[0] : undefined
      if (pattern) restrictions.push(`        <xs:pattern value="${escapeXml(String(pattern))}"/>`)
    }
  }
  return restrictions
}

function escapeXml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
}

export default defineTemplate({
  name: 'XML Schema (XSD)',
  description: 'Generate XML Schema Definition types from SQL schema',
  language: 'xml',

  generate(ctx) {
    const schema = enrichRealm(ctx)
    const lines: string[] = [
      '<?xml version="1.0" encoding="UTF-8"?>',
      '<!-- Generated by @sqldoc/templates/xsd. DO NOT EDIT -->',
      '<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">',
      '',
    ]

    // Enums as simpleType restrictions
    for (const e of schema.enums) {
      lines.push(`  <xs:simpleType name="${e.pascalName}">`)
      lines.push(`    <xs:restriction base="xs:string">`)
      for (const v of e.values) {
        lines.push(`      <xs:enumeration value="${escapeXml(v)}"/>`)
      }
      lines.push(`    </xs:restriction>`)
      lines.push(`  </xs:simpleType>`)
      lines.push('')
    }

    for (const table of activeTables(schema)) {
      lines.push(`  <xs:complexType name="${table.pascalName}">`)
      lines.push('    <xs:sequence>')

      for (const col of table.columns) {
        if (col.category === 'enum' && col.enumValues?.length) {
          // Reference the enum simpleType
          const enumTypeName = toPascalCase(col.pgType)
          lines.push(
            `      <xs:element name="${col.camelName}" type="${enumTypeName}"${col.nullable ? ' minOccurs="0"' : ''}/>`,
          )
        } else {
          const xsdType = pgToXsd(col.pgType)
          const restrictions = buildRestrictions(col)

          if (restrictions.length > 0) {
            lines.push(`      <xs:element name="${col.camelName}"${col.nullable ? ' minOccurs="0"' : ''}>`)
            lines.push('        <xs:simpleType>')
            lines.push(`          <xs:restriction base="${xsdType}">`)
            lines.push(...restrictions.map((r) => `  ${r}`))
            lines.push('          </xs:restriction>')
            lines.push('        </xs:simpleType>')
            lines.push('      </xs:element>')
          } else {
            lines.push(
              `      <xs:element name="${col.camelName}" type="${xsdType}"${col.nullable ? ' minOccurs="0"' : ''}/>`,
            )
          }
        }
      }

      lines.push('    </xs:sequence>')
      lines.push('  </xs:complexType>')
      lines.push('')
    }

    // Views (read-only)
    for (const view of schema.views.filter((v) => !v.skipped)) {
      lines.push(`  <!-- Read-only (from view) -->`)
      lines.push(`  <xs:complexType name="${view.pascalName}">`)
      lines.push('    <xs:sequence>')

      for (const col of view.columns) {
        if (col.category === 'enum' && col.enumValues?.length) {
          const enumTypeName = toPascalCase(col.pgType)
          lines.push(
            `      <xs:element name="${col.camelName}" type="${enumTypeName}"${col.nullable ? ' minOccurs="0"' : ''}/>`,
          )
        } else {
          const xsdType = pgToXsd(col.pgType)
          const restrictions = buildRestrictions(col)

          if (restrictions.length > 0) {
            lines.push(`      <xs:element name="${col.camelName}"${col.nullable ? ' minOccurs="0"' : ''}>`)
            lines.push('        <xs:simpleType>')
            lines.push(`          <xs:restriction base="${xsdType}">`)
            lines.push(...restrictions.map((r) => `  ${r}`))
            lines.push('          </xs:restriction>')
            lines.push('        </xs:simpleType>')
            lines.push('      </xs:element>')
          } else {
            lines.push(
              `      <xs:element name="${col.camelName}" type="${xsdType}"${col.nullable ? ' minOccurs="0"' : ''}/>`,
            )
          }
        }
      }

      lines.push('    </xs:sequence>')
      lines.push('  </xs:complexType>')
      lines.push('')
    }

    lines.push('</xs:schema>')
    lines.push('')

    return { files: [{ path: 'schema.xsd', content: lines.join('\n') }] }
  },
})
