// Generated by @sqldoc/templates/gorm -- DO NOT EDIT
package models

import "time"

type Adoption struct {
	Id int32 `gorm:"primaryKey;type:int;not null" json:"id,omitempty"`
	PetId int32 `gorm:"type:int;not null;foreignKey:id" json:"pet_id,omitempty"`
	OwnerId int32 `gorm:"type:int;not null;foreignKey:id" json:"owner_id,omitempty"`
	AdoptedAt time.Time `gorm:"type:datetime2(7);not null;default:getdate()" json:"adopted_at,omitempty"`
	AdoptionFee string `gorm:"type:decimal(10,2)(10,2);not null;default:0" json:"adoption_fee,omitempty"`
	UpdatedBy *string `gorm:"type:nvarchar(max)" json:"updated_by,omitempty"`
}

type AdoptionsAuditLog struct {
	Id int64 `gorm:"primaryKey;type:bigint;not null" json:"id,omitempty"`
	TableName string `gorm:"type:nvarchar(max);not null" json:"table_name,omitempty"`
	Operation string `gorm:"type:nvarchar(max);not null" json:"operation,omitempty"`
	OldData *string `gorm:"type:nvarchar(max)" json:"old_data,omitempty"`
	NewData *string `gorm:"type:nvarchar(max)" json:"new_data,omitempty"`
	ChangedAt time.Time `gorm:"type:datetime2(7);not null;default:getdate()" json:"changed_at,omitempty"`
}

type Category struct {
	Id int32 `gorm:"primaryKey;type:int;not null" json:"id,omitempty"`
	Name string `gorm:"type:nvarchar(100)(100);not null" json:"name,omitempty"`
	Description *string `gorm:"type:nvarchar(max)" json:"description,omitempty"`
}

type LegacyInventory struct {
	Id int32 `gorm:"primaryKey;type:int;not null" json:"id,omitempty"`
	ItemName *string `gorm:"type:nvarchar(200)(200)" json:"item_name,omitempty"`
	OldSku *string `gorm:"type:nvarchar(50)(50)" json:"old_sku,omitempty"`
	Quantity *int32 `gorm:"type:int;default:0" json:"quantity,omitempty"`
}

type Location struct {
	Id int32 `gorm:"primaryKey;type:int;not null" json:"id,omitempty"`
	Name string `gorm:"type:nvarchar(200)(200);not null" json:"name,omitempty"`
	Address string `gorm:"type:nvarchar(max);not null" json:"address,omitempty"`
	City string `gorm:"type:nvarchar(100)(100);not null" json:"city,omitempty"`
	Zip *string `gorm:"type:nvarchar(20)(20)" json:"zip,omitempty"`
}

type MedicalRecord struct {
	Id int32 `gorm:"primaryKey;type:int;not null" json:"id,omitempty"`
	PetId int32 `gorm:"type:int;not null;foreignKey:id" json:"pet_id,omitempty"`
	VisitDate time.Time `gorm:"type:date;not null;default:CONVERT([date],getdate())" json:"visit_date,omitempty"`
	Diagnosis string `gorm:"type:nvarchar(max);not null" json:"diagnosis,omitempty"`
	Treatment *string `gorm:"type:nvarchar(max)" json:"treatment,omitempty"`
	VetName *string `gorm:"type:nvarchar(150)(150)" json:"vet_name,omitempty"`
}

type Owner struct {
	Id int32 `gorm:"primaryKey;type:int;not null" json:"id,omitempty"`
	Name string `gorm:"type:nvarchar(150)(150);not null" json:"name,omitempty"`
	Email string `gorm:"type:nvarchar(255)(255);not null" json:"email,omitempty"`
	Phone *string `gorm:"type:nvarchar(20)(20)" json:"phone,omitempty"`
	CreatedAt *time.Time `gorm:"type:datetime2(7);default:getdate()" json:"created_at,omitempty"`
}

type Pet struct {
	Id int32 `gorm:"primaryKey;type:int;not null" json:"id,omitempty"`
	CategoryId *int32 `gorm:"type:int;foreignKey:id" json:"category_id,omitempty"`
	Name string `gorm:"type:nvarchar(100)(100);not null" json:"name,omitempty"`
	Sku string `gorm:"type:nvarchar(20)(20);not null" json:"sku,omitempty"`
	Price string `gorm:"type:decimal(10,2)(10,2);not null;default:0" json:"price,omitempty"`
	InternalNotes *string `gorm:"type:nvarchar(max)" json:"internal_notes,omitempty"`
	Status string `gorm:"type:nvarchar(20)(20);not null;default:available" json:"status,omitempty"`
	CreatedAt *time.Time `gorm:"type:datetime2(7);default:getdate()" json:"created_at,omitempty"`
}

type Review struct {
	Id int32 `gorm:"primaryKey;type:int;not null" json:"id,omitempty"`
	PetId int32 `gorm:"type:int;not null;foreignKey:id" json:"pet_id,omitempty"`
	OwnerId int32 `gorm:"type:int;not null;foreignKey:id" json:"owner_id,omitempty"`
	Rating int32 `gorm:"type:int;not null" json:"rating,omitempty"`
	Body *string `gorm:"type:nvarchar(max)" json:"body,omitempty"`
	LocationId *int32 `gorm:"type:int;foreignKey:id" json:"location_id,omitempty"`
	CreatedAt *time.Time `gorm:"type:datetime2(7);default:getdate()" json:"created_at,omitempty"`
}

type StaffAuditLog struct {
	Id int64 `gorm:"primaryKey;type:bigint;not null" json:"id,omitempty"`
	TableName string `gorm:"type:nvarchar(max);not null" json:"table_name,omitempty"`
	Operation string `gorm:"type:nvarchar(max);not null" json:"operation,omitempty"`
	OldData *string `gorm:"type:nvarchar(max)" json:"old_data,omitempty"`
	NewData *string `gorm:"type:nvarchar(max)" json:"new_data,omitempty"`
	ChangedAt time.Time `gorm:"type:datetime2(7);not null;default:getdate()" json:"changed_at,omitempty"`
}
