import { defineTemplate } from '@sqldoc/ns-codegen'
import { activeTables, enrichRealm } from '../helpers/enrich.ts'
import { toCamelCase, toPascalCase } from '../helpers/naming.ts'
import { JSON_TYPE_DECLARATION, pgToTs, type TsTypeOptions } from '../types/pg-to-ts.ts'

export const configSchema = {
  dateType: {
    type: 'enum',
    values: ['Date', 'dayjs', 'luxon', 'string'],
    description: 'How to represent date/time types',
  },
  bigintType: {
    type: 'enum',
    values: ['number', 'bigint', 'string'],
    description: 'How to represent bigint/bigserial columns',
  },
} as const

export default defineTemplate({
  name: 'Kysely Database',
  description: 'Generate Kysely Database interface and table types from SQL schema',
  language: 'typescript',
  configSchema,

  generate(ctx) {
    const config = ctx.config ?? {}
    const options: TsTypeOptions = {
      dateType: config.dateType,
      bigintType: config.bigintType,
      nullableStyle: 'null-union',
    }

    const schema = enrichRealm(ctx)
    // Check if any column uses Json type
    const allCols = [...schema.tables.flatMap((t) => t.columns), ...schema.views.flatMap((v) => v.columns)]
    const hasJson = allCols.some((c) => c.category === 'json' || c.pgType === 'json' || c.pgType === 'jsonb')

    let needsSql = false

    const lines: string[] = [
      '// Generated by @sqldoc/templates/kysely -- DO NOT EDIT',
      '',
      '', // placeholder for imports — filled at end
      '',
    ]

    if (hasJson) {
      lines.push(JSON_TYPE_DECLARATION)
      lines.push('')
    }

    // Enums
    for (const e of schema.enums) {
      const values = e.values.map((v) => `'${v}'`).join(' | ')
      lines.push(`export type ${e.pascalName} = ${values}`)
      lines.push('')
    }

    // Composite types (collected from columns and function return types)
    const composites = new Map<string, Array<{ name: string; type: string }>>()
    for (const table of schema.tables) {
      for (const col of table.columns) {
        if (col.category === 'composite' && col.compositeFields?.length && !composites.has(col.pgType)) {
          composites.set(col.pgType, col.compositeFields)
        }
      }
    }
    for (const fn of schema.functions) {
      if (fn.returnType?.category === 'composite' && fn.returnType.compositeFields?.length) {
        // Strip "SETOF " prefix to get the actual composite type name
        const typeName = fn.returnType.type.replace(/^setof\s+/i, '')
        if (!composites.has(typeName)) {
          composites.set(typeName, fn.returnType.compositeFields)
        }
      }
    }
    for (const [name, fields] of composites) {
      const typeName = toPascalCase(name)
      lines.push(`export interface ${typeName} {`)
      for (const f of fields) {
        lines.push(`  ${toCamelCase(f.name)}: ${pgToTs(f.type, false, options)}`)
      }
      lines.push('}')
      lines.push('')
    }

    // Generate per-table interfaces
    const tableEntries: string[] = []

    for (const table of activeTables(schema)) {
      const interfaceName = table.pascalName

      lines.push(`export interface ${interfaceName} {`)

      for (const col of table.columns) {
        let tsType = resolveType(col, options)

        // Wrap auto-generated columns in Generated<T>
        if (col.isSerial || col.raw.default !== undefined) {
          tsType = `Generated<${tsType}>`
        }

        lines.push(`  ${col.name}: ${tsType}`)
      }

      lines.push('}')
      lines.push('')

      tableEntries.push(`  '${table.sqlName}': ${interfaceName}`)
    }

    // Views (read-only)
    for (const view of schema.views.filter((v) => !v.skipped)) {
      const interfaceName = view.pascalName

      lines.push(`/** Read-only (from view) */`)
      lines.push(`export interface ${interfaceName} {`)

      for (const col of view.columns) {
        const tsType = resolveType(col, options)
        lines.push(`  ${col.name}: ${tsType}`)
      }

      lines.push('}')
      lines.push('')

      tableEntries.push(`  '${view.sqlName}': ${interfaceName}`)
    }

    // Generate the Database interface
    lines.push('export interface Database {')
    lines.push(tableEntries.join('\n'))
    lines.push('}')
    lines.push('')

    // Functions — generate typesafe callable helpers
    const fnDefs: string[] = []
    for (const fn of schema.functions) {
      const retRaw = fn.returnType?.type?.toLowerCase() ?? ''
      if (retRaw === 'trigger') continue

      const filteredArgs = fn.args.filter((a) => !a.name?.startsWith('_') && (a as any).mode !== 'OUT')

      // Build parameter list
      const usedNames = new Set<string>()
      const params = filteredArgs.map((a, i) => {
        const argType = pgToTs(a.type, false, options, a.category as any)
        let argName = a.name ? toCamelCase(a.name) : `arg${i + 1}`
        if (usedNames.has(argName)) argName = `${argName}${i + 1}`
        usedNames.add(argName)
        return { name: argName, type: argType }
      })

      const paramStr = params.map((p) => `${p.name}: ${p.type}`).join(', ')
      const sqlArgs = params.map((p) => `\${${p.name}}`).join(', ')
      const fnName = toCamelCase(fn.name)

      // Determine return type and query style
      if (retRaw.startsWith('setof ')) {
        const tableName = retRaw.replace('setof ', '')
        const table = schema.tables.find((t) => t.name === tableName || t.sqlName === tableName)
        const rowType = table?.pascalName ?? toPascalCase(tableName)

        fnDefs.push(`export function ${fnName}(db: Kysely<Database>, ${paramStr}) {`)
        fnDefs.push(`  return db.selectFrom(sql<${rowType}>\`${fn.name}(${sqlArgs})\`.as('t')).selectAll().execute()`)
        fnDefs.push('}')
        fnDefs.push('')
      } else if (fn.returnType) {
        const retType = pgToTs(fn.returnType.type, false, options, fn.returnType.category as any)

        fnDefs.push(`export async function ${fnName}(db: Kysely<Database>, ${paramStr}): Promise<${retType}> {`)
        fnDefs.push(
          `  const { val } = await sql<{ val: ${retType} }>\`SELECT ${fn.name}(${sqlArgs}) AS val\`.execute(db).then(r => r.rows[0]!)`,
        )
        fnDefs.push('  return val')
        fnDefs.push('}')
        fnDefs.push('')
      }
    }

    if (fnDefs.length > 0) {
      needsSql = true
      lines.push(...fnDefs)
    }

    // Fill in the import line (index 2) now that we know if sql/Kysely are needed
    if (needsSql) {
      lines[2] = "import { sql, type Kysely, type Generated } from 'kysely'"
    } else {
      lines[2] = "import type { Generated } from 'kysely'"
    }

    return {
      files: [
        {
          path: 'database.ts',
          content: lines.join('\n'),
        },
      ],
    }

    function resolveType(col: any, options: TsTypeOptions): string {
      if (col.typeOverride) return col.typeOverride
      if (col.category === 'enum' && col.enumValues?.length) {
        return col.nullable ? `${toPascalCase(col.pgType)} | null` : toPascalCase(col.pgType)
      }
      if (col.category === 'composite' && col.compositeFields?.length) {
        const compositeType = toPascalCase(col.pgType)
        return col.nullable ? `${compositeType} | null` : compositeType
      }
      return pgToTs(col.pgType, col.nullable, options, col.category)
    }
  },
})
