import { defineTemplate } from '@sqldoc/ns-codegen'
import { activeTables, enrichRealm } from '../helpers/enrich.ts'
import { toCamelCase } from '../helpers/naming.ts'
import {
  collectCompositeTypes,
  emitCompositeInterfaces,
  hasJsonTypes,
  inputFunctionParams,
  qualifiedFunctionSqlName,
  resolveFunctionReturnType,
  resolveTsColumnType,
} from '../helpers/typescript.ts'
import { JSON_TYPE_DECLARATION, type TsTypeOptions } from '../types/pg-to-ts.ts'

export const configSchema = {
  dateType: {
    type: 'enum',
    values: ['Date', 'dayjs', 'luxon', 'string'],
    description: 'How to represent date/time types',
  },
  bigintType: {
    type: 'enum',
    values: ['number', 'bigint', 'string'],
    description: 'How to represent bigint/bigserial columns',
  },
} as const

export default defineTemplate({
  name: 'Kysely Database',
  description: 'Generate Kysely Database interface and table types from SQL schema',
  language: 'typescript',
  configSchema,

  generate(ctx) {
    const config = ctx.config ?? {}
    const options: TsTypeOptions = {
      dateType: config.dateType,
      bigintType: config.bigintType,
      nullableStyle: 'null-union',
    }

    const schema = enrichRealm(ctx)
    let needsSql = false

    const lines: string[] = [
      '// Generated by @sqldoc/templates/kysely -- DO NOT EDIT',
      '',
      '', // placeholder for imports — filled at end
      '',
    ]

    if (hasJsonTypes(schema)) {
      lines.push(JSON_TYPE_DECLARATION)
      lines.push('')
    }

    // Enums
    for (const e of schema.enums) {
      const values = e.values.map((v) => `'${v}'`).join(' | ')
      lines.push(`export type ${e.pascalName} = ${values}`)
      lines.push('')
    }

    // Composite types (collected from columns and function return types)
    const composites = collectCompositeTypes(schema)
    emitCompositeInterfaces(lines, composites, options)

    // Generate per-table interfaces
    const tableEntries: string[] = []

    for (const table of activeTables(schema)) {
      const interfaceName = table.pascalName

      lines.push(`export interface ${interfaceName} {`)

      for (const col of table.columns) {
        let tsType = resolveTsColumnType(col, options)

        // Wrap auto-generated columns in Generated<T>
        if (col.isSerial || col.raw.default !== undefined) {
          tsType = `Generated<${tsType}>`
        }

        lines.push(`  ${col.name}: ${tsType}`)
      }

      lines.push('}')
      lines.push('')

      tableEntries.push(`  '${table.sqlName}': ${interfaceName}`)
    }

    // Views (read-only)
    for (const view of schema.views.filter((v) => !v.skipped)) {
      const interfaceName = view.pascalName

      lines.push(`/** Read-only (from view) */`)
      lines.push(`export interface ${interfaceName} {`)

      for (const col of view.columns) {
        const tsType = resolveTsColumnType(col, options)
        lines.push(`  ${col.name}: ${tsType}`)
      }

      lines.push('}')
      lines.push('')

      tableEntries.push(`  '${view.sqlName}': ${interfaceName}`)
    }

    // Generate the Database interface
    lines.push('export interface Database {')
    lines.push(tableEntries.join('\n'))
    lines.push('}')
    lines.push('')

    // Functions — generate typesafe callable helpers
    const fnDefs: string[] = []
    for (const fn of schema.functions) {
      const retRaw = fn.returnType?.type?.toLowerCase() ?? ''
      if (retRaw === 'trigger') continue

      const params = inputFunctionParams(fn, options)
      const paramStr = params.map((p) => `${p.name}: ${p.type}`).join(', ')
      const sqlArgs = params.map((p) => `\${${p.name}}`).join(', ')
      const fnName = toCamelCase(fn.name)
      const sqlFnName = qualifiedFunctionSqlName(fn, ctx.defaultSchema)

      // Determine return type and query style
      if (retRaw.startsWith('setof ')) {
        const rowType = resolveFunctionReturnType(fn, schema, options, composites).replace(/\[\]$/, '')

        fnDefs.push(`export function ${fnName}(db: Kysely<Database>, ${paramStr}) {`)
        fnDefs.push(`  return db.selectFrom(sql<${rowType}>\`${sqlFnName}(${sqlArgs})\`.as('t')).selectAll().execute()`)
        fnDefs.push('}')
        fnDefs.push('')
      } else if (fn.returnType) {
        const retType = resolveFunctionReturnType(fn, schema, options, composites)

        fnDefs.push(`export async function ${fnName}(db: Kysely<Database>, ${paramStr}): Promise<${retType}> {`)
        fnDefs.push(
          `  const { val } = await sql<{ val: ${retType} }>\`SELECT ${sqlFnName}(${sqlArgs}) AS val\`.execute(db).then(r => r.rows[0]!)`,
        )
        fnDefs.push('  return val')
        fnDefs.push('}')
        fnDefs.push('')
      }
    }

    if (fnDefs.length > 0) {
      needsSql = true
      lines.push(...fnDefs)
    }

    // Fill in the import line (index 2) now that we know if sql/Kysely are needed
    if (needsSql) {
      lines[2] = "import { sql, type Kysely, type Generated } from 'kysely'"
    } else {
      lines[2] = "import type { Generated } from 'kysely'"
    }

    return {
      files: [
        {
          path: 'database.ts',
          content: lines.join('\n'),
        },
      ],
    }
  },
})
