import * as fs from 'node:fs'
import * as path from 'node:path'

/**
 * Scan .sqldoc/node_modules for installed @sqldoc namespace plugins,
 * and generate .sqldoc/config.d.ts with a typed SqldocConfig interface.
 *
 * Base config fields are imported from @sqldoc/core so they stay in sync.
 * Only the namespaces block is generated based on installed plugins.
 */
export function generateConfigTypes(sqldocDir: string): void {
  const nodeModules = path.join(sqldocDir, 'node_modules', '@sqldoc')
  if (!fs.existsSync(nodeModules)) return

  const imports: string[] = ["import type { ProjectConfig as BaseProjectConfig } from '@sqldoc/core'"]
  const namespaceFields: string[] = []

  const dirs = fs.readdirSync(nodeModules).sort()
  for (const dir of dirs) {
    if (!dir.startsWith('ns-')) continue

    const pkgPath = path.join(nodeModules, dir)
    const pkgJsonPath = path.join(pkgPath, 'package.json')
    if (!fs.existsSync(pkgJsonPath)) continue

    const nsName = dir.replace('ns-', '')
    const pkgName = `@sqldoc/${dir}`

    const configTypeName = findConfigTypeName(pkgPath, nsName)

    if (configTypeName) {
      imports.push(`import type { ${configTypeName} } from '${pkgName}'`)
      namespaceFields.push(`    ${nsName}?: Partial<${configTypeName}>`)
    } else {
      namespaceFields.push(`    ${nsName}?: Record<string, unknown>`)
    }
  }

  const namespacesBlock =
    namespaceFields.length > 0
      ? `  namespaces?: {
${namespaceFields.join('\n')}
  }`
      : `  namespaces?: Record<string, Record<string, unknown>>`

  const content = `// Auto-generated by sqldoc -- DO NOT EDIT
// Regenerated on: sqldoc init, sqldoc add, sqldoc codegen
${imports.join('\n')}

interface ProjectConfig extends BaseProjectConfig {
${namespacesBlock}
}

export type SqldocConfig = ProjectConfig | ProjectConfig[]
export type Config = SqldocConfig
`

  fs.writeFileSync(path.join(sqldocDir, 'config.d.ts'), content)
}

function findConfigTypeName(pkgPath: string, _nsName: string): string | null {
  const candidates = ['src/index.ts', 'index.ts', 'src/index.js', 'index.js']
  for (const candidate of candidates) {
    const filePath = path.join(pkgPath, candidate)
    if (!fs.existsSync(filePath)) continue

    const content = fs.readFileSync(filePath, 'utf-8')
    const match = content.match(/export\s+(?:type\s+)?{\s*[^}]*\b(\w+Config)\b/)
    if (match) return match[1]
  }

  return null
}
