import type { DocsAnnotation, MergedSchema, MergedTable, MergedView } from '../types.ts'

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

function getTableAnnotations(annotations: DocsAnnotation[], tableName: string): string[] {
  return annotations.filter((a) => a.object.toLowerCase() === tableName.toLowerCase()).map((a) => a.text)
}

function getExtraCell(data: Map<string, string>, tableName: string, colName: string, header: string): string {
  const key = `${tableName.toLowerCase()}:${colName.toLowerCase()}:${header}`
  return data.get(key) ?? '-'
}

function renderAnnotationBadges(annotations: string[]): string {
  if (annotations.length === 0) return ''
  const badges = annotations.map((a) => `<span class="annotation">${escapeHtml(a)}</span>`).join('\n      ')
  return `    <div class="annotations">\n      ${badges}\n    </div>`
}

function renderTableSection(table: MergedTable, schema: MergedSchema): string {
  const parts: string[] = []
  const extras = schema.extraColumnHeaders

  parts.push(`  <section id="${escapeHtml(table.name)}">`)

  let heading = `    <h3>${escapeHtml(table.name)}`
  if (table.isGenerated && table.generatedBy) {
    heading += ` <span class="generated-badge">Generated by @${escapeHtml(table.generatedBy)}</span>`
  }
  heading += '</h3>'
  parts.push(heading)

  if (table.previously) {
    parts.push(`    <p class="previously">formerly: ${escapeHtml(table.previously)}</p>`)
  }

  if (table.description) {
    parts.push(`    <p class="description">${escapeHtml(table.description)}</p>`)
  }

  const tableAnnots = getTableAnnotations(schema.annotations, table.name)
  const annotBadges = renderAnnotationBadges(tableAnnots)
  if (annotBadges) parts.push(annotBadges)

  // Column table with extra plugin columns
  const extraHeaders = extras.map((h) => `          <th>${escapeHtml(h)}</th>`).join('\n')
  const rows = table.columns
    .map((col) => {
      const pk = col.isPrimaryKey ? 'Y' : '-'
      const fk = col.isForeignKey ? 'Y' : '-'
      const nullable = col.nullable ? 'Yes' : 'No'
      let desc = col.description ? escapeHtml(col.description) : '-'
      if (col.previously) {
        const formerly = `<em class="previously">formerly: ${escapeHtml(col.previously)}</em>`
        desc = desc === '-' ? formerly : `${desc} ${formerly}`
      }
      const extraCells = extras
        .map((h) => {
          const val = getExtraCell(schema.extraColumnData, table.name, col.name, h)
          return `        <td>${val === '-' ? '-' : escapeHtml(val)}</td>`
        })
        .join('\n')
      return `      <tr>
        <td>${escapeHtml(col.name)}</td>
        <td>${escapeHtml(col.type)}</td>
        <td>${nullable}</td>
        <td>${pk}</td>
        <td>${fk}</td>
        <td>${desc}</td>
${extraCells}
      </tr>`
    })
    .join('\n')

  parts.push(`    <table>
      <thead>
        <tr>
          <th>Column</th>
          <th>Type</th>
          <th>Nullable</th>
          <th>PK</th>
          <th>FK</th>
          <th>Description</th>
${extraHeaders}
        </tr>
      </thead>
      <tbody>
${rows}
      </tbody>
    </table>`)

  if (table.foreignKeys.length > 0) {
    parts.push('    <h4>Foreign Keys</h4>')
    parts.push('    <ul>')
    for (const fk of table.foreignKeys) {
      const cols = fk.columns.join(', ')
      const refCols = fk.references.columns.join(', ')
      parts.push(
        `      <li>${escapeHtml(fk.name)}: ${escapeHtml(cols)} -&gt; ${escapeHtml(fk.references.table)}(${escapeHtml(refCols)})</li>`,
      )
    }
    parts.push('    </ul>')
  }

  if (table.indexes.length > 0) {
    parts.push('    <h4>Indexes</h4>')
    parts.push('    <ul>')
    for (const idx of table.indexes) {
      const idxParts = idx.parts.map((p) => p.column).join(', ')
      const unique = idx.unique ? ' UNIQUE' : ''
      parts.push(`      <li>${escapeHtml(idx.name)} (${escapeHtml(idxParts)})${unique}</li>`)
    }
    parts.push('    </ul>')
  }

  parts.push('  </section>')
  return parts.join('\n')
}

function renderViewSection(view: MergedView): string {
  const parts: string[] = []

  parts.push(`  <section id="${escapeHtml(view.name)}">`)
  parts.push(`    <h3>${escapeHtml(view.name)}</h3>`)

  if (view.description) {
    parts.push(`    <p class="description">${escapeHtml(view.description)}</p>`)
  }

  const rows = view.columns
    .map((col) => {
      const desc = col.description ? escapeHtml(col.description) : '-'
      const nullable = col.nullable ? 'Yes' : 'No'
      return `      <tr>
        <td>${escapeHtml(col.name)}</td>
        <td>${escapeHtml(col.type)}</td>
        <td>${nullable}</td>
        <td>-</td>
        <td>-</td>
        <td>${desc}</td>
      </tr>`
    })
    .join('\n')

  parts.push(`    <table>
      <thead>
        <tr>
          <th>Column</th>
          <th>Type</th>
          <th>Nullable</th>
          <th>PK</th>
          <th>FK</th>
          <th>Description</th>
        </tr>
      </thead>
      <tbody>
${rows}
      </tbody>
    </table>`)

  parts.push('  </section>')
  return parts.join('\n')
}

export function renderHtml(schema: MergedSchema): string {
  const tableLinks = schema.tables
    .map((t) => `    <a href="#${escapeHtml(t.name)}">${escapeHtml(t.name)}</a>`)
    .join('\n')

  const viewLinks = schema.views.map((v) => `    <a href="#${escapeHtml(v.name)}">${escapeHtml(v.name)}</a>`).join('\n')

  const viewsSidebar = schema.views.length > 0 ? `\n    <h2>Views</h2>\n${viewLinks}` : ''

  const tableSections = schema.tables.map((t) => renderTableSection(t, schema)).join('\n')
  const viewSections = schema.views.map(renderViewSection).join('\n')

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(schema.title)}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; display: flex; }
    .sidebar { width: 260px; height: 100vh; position: fixed; overflow-y: auto; background: #f8f9fa; border-right: 1px solid #dee2e6; padding: 16px; }
    .sidebar h1 { font-size: 18px; margin-bottom: 16px; }
    .sidebar h2 { font-size: 14px; text-transform: uppercase; color: #6c757d; margin: 16px 0 8px; }
    .sidebar a { display: block; padding: 4px 8px; color: #212529; text-decoration: none; font-size: 14px; border-radius: 4px; }
    .sidebar a:hover { background: #e9ecef; }
    .sidebar a.active { background: #0d6efd; color: white; }
    .content { margin-left: 260px; padding: 32px; max-width: 1100px; }
    table { border-collapse: collapse; width: 100%; margin: 16px 0; }
    th, td { border: 1px solid #dee2e6; padding: 8px 12px; text-align: left; }
    th { background: #f8f9fa; }
    .annotation { display: inline-block; background: #d1ecf1; color: #0c5460; border-radius: 4px; padding: 2px 8px; font-size: 12px; margin: 2px; }
    .annotations { margin: 8px 0; }
    .generated-badge { display: inline-block; background: #fff3cd; color: #856404; border-radius: 4px; padding: 2px 6px; font-size: 12px; }
    .description { color: #495057; margin: 8px 0; }
    .previously { color: #6c757d; font-style: italic; font-size: 13px; margin: 4px 0; display: block; }
    h3 { margin-top: 32px; padding-top: 16px; border-top: 1px solid #dee2e6; }
    .mermaid { margin: 24px 0; padding: 16px; background: #f8f9fa; border-radius: 8px; }
    .timestamp { color: #6c757d; font-size: 14px; }
    h4 { margin: 16px 0 8px; font-size: 15px; }
    ul { margin: 0 0 16px 24px; }
    li { margin: 4px 0; }
  </style>
</head>
<body>
  <nav class="sidebar">
    <h1>${escapeHtml(schema.title)}</h1>
    <h2>Tables</h2>
${tableLinks}${viewsSidebar}
  </nav>
  <main class="content">
    <section id="er-diagram">
      <h2>Entity Relationship Diagram</h2>
      <pre class="mermaid">${escapeHtml(schema.mermaidERD)}${schema.extraRelationships
        .map((rel) => `\n    ${rel.from} ||..o{ ${rel.to} : "${rel.label}"`)
        .join('')}</pre>
    </section>
${tableSections}
${viewSections}
  </main>
  <script type="module">
    import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs';
    mermaid.initialize({ startOnLoad: true });

    const observer = new IntersectionObserver((entries) => {
      entries.forEach(entry => {
        if (entry.isIntersecting) {
          document.querySelectorAll('.sidebar a').forEach(a => a.classList.remove('active'));
          const link = document.querySelector('.sidebar a[href="#' + entry.target.id + '"]');
          if (link) link.classList.add('active');
        }
      });
    }, { threshold: 0.3 });
    document.querySelectorAll('section[id]').forEach(s => observer.observe(s));
  </script>
</body>
</html>`
}
