import type { DocsAnnotation, MergedSchema, MergedTable, MergedView } from '../types.ts'

function getTableAnnotations(annotations: DocsAnnotation[], tableName: string): string[] {
  return annotations.filter((a) => a.object.toLowerCase() === tableName.toLowerCase()).map((a) => a.text)
}

function getExtraCell(data: Map<string, string>, tableName: string, colName: string, header: string): string {
  const key = `${tableName.toLowerCase()}:${colName.toLowerCase()}:${header}`
  return data.get(key) ?? '-'
}

function renderTableSection(table: MergedTable, schema: MergedSchema): string {
  const lines: string[] = []
  const extras = schema.extraColumnHeaders

  let heading = `### ${table.name}`
  if (table.isGenerated && table.generatedBy) {
    heading += ` (Generated by @${table.generatedBy})`
  }
  lines.push(heading)
  lines.push('')

  if (table.previously) {
    lines.push(`*formerly: ${table.previously}*`)
    lines.push('')
  }

  if (table.description) {
    lines.push(table.description)
    lines.push('')
  }

  const tableAnnots = getTableAnnotations(schema.annotations, table.name)
  if (tableAnnots.length > 0) {
    lines.push(tableAnnots.map((a) => `> ${a}`).join('\n'))
    lines.push('')
  }

  // Column table header
  const baseHeaders = ['Column', 'Type', 'Nullable', 'PK', 'FK', 'Description']
  const allHeaders = [...baseHeaders, ...extras]
  lines.push(`| ${allHeaders.join(' | ')} |`)
  lines.push(`|${allHeaders.map(() => '------').join('|')}|`)

  for (const col of table.columns) {
    const pk = col.isPrimaryKey ? 'Y' : '-'
    const fk = col.isForeignKey ? 'Y' : '-'
    const nullable = col.nullable ? 'Yes' : 'No'
    let desc = col.description ?? '-'
    if (col.previously) {
      const formerly = `*formerly: ${col.previously}*`
      desc = desc === '-' ? formerly : `${desc} ${formerly}`
    }
    const baseCells = [col.name, col.type, nullable, pk, fk, desc]
    const extraCells = extras.map((h) => getExtraCell(schema.extraColumnData, table.name, col.name, h))
    lines.push(`| ${[...baseCells, ...extraCells].join(' | ')} |`)
  }
  lines.push('')

  if (table.foreignKeys.length > 0) {
    lines.push('#### Foreign Keys')
    lines.push('')
    for (const fk of table.foreignKeys) {
      const cols = fk.columns.join(', ')
      const refCols = fk.references.columns.join(', ')
      lines.push(`- ${fk.name}: ${cols} -> ${fk.references.table}(${refCols})`)
    }
    lines.push('')
  }

  if (table.indexes.length > 0) {
    lines.push('#### Indexes')
    lines.push('')
    for (const idx of table.indexes) {
      const parts = idx.parts.map((p) => p.column).join(', ')
      const unique = idx.unique ? ' UNIQUE' : ''
      lines.push(`- ${idx.name} (${parts})${unique}`)
    }
    lines.push('')
  }

  return lines.join('\n')
}

function renderViewSection(view: MergedView): string {
  const lines: string[] = []

  lines.push(`### ${view.name}`)
  lines.push('')

  if (view.description) {
    lines.push(view.description)
    lines.push('')
  }

  lines.push('| Column | Type | Nullable | PK | FK | Description |')
  lines.push('|------|------|----------|----|----|-------------|')
  for (const col of view.columns) {
    const desc = col.description ?? '-'
    const nullable = col.nullable ? 'Yes' : 'No'
    lines.push(`| ${col.name} | ${col.type} | ${nullable} | - | - | ${desc} |`)
  }
  lines.push('')

  return lines.join('\n')
}

export function renderMarkdown(schema: MergedSchema): string {
  const lines: string[] = []

  lines.push(`# ${schema.title}`)
  lines.push('')
  lines.push(`*Generated: ${schema.generatedAt}*`)
  lines.push('')

  lines.push('## Contents')
  lines.push('')
  if (schema.tables.length > 0) {
    lines.push('**Tables:**')
    for (const table of schema.tables) {
      lines.push(`- [${table.name}](#${table.name})`)
    }
    lines.push('')
  }
  if (schema.views.length > 0) {
    lines.push('**Views:**')
    for (const view of schema.views) {
      lines.push(`- [${view.name}](#${view.name})`)
    }
    lines.push('')
  }

  lines.push('## Entity Relationship Diagram')
  lines.push('')
  lines.push('```mermaid')
  lines.push(schema.mermaidERD)
  for (const rel of schema.extraRelationships) {
    lines.push(`    ${rel.from} ||..o{ ${rel.to} : "${rel.label}"`)
  }
  lines.push('```')
  lines.push('')

  if (schema.tables.length > 0) {
    lines.push('## Tables')
    lines.push('')
    for (const table of schema.tables) {
      lines.push(renderTableSection(table, schema))
    }
  }

  if (schema.views.length > 0) {
    lines.push('## Views')
    lines.push('')
    for (const view of schema.views) {
      lines.push(renderViewSection(view))
    }
  }

  return lines.join('\n')
}
