// Generated by @sqldoc/templates/swift-codable -- DO NOT EDIT

import Foundation

struct Post: Codable {
    let id: Int64
    let userId: Int64
    let title: String
    let body: String
    let publishedAt: Date?
    let viewCount: Int
    let rating: Double?

    enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case title
        case body
        case publishedAt = "published_at"
        case viewCount = "view_count"
        case rating
    }
}

struct Comment: Codable {
    let id: Int64
    let postId: Int64
    let userId: Int64
    let parentId: Int64?
    let content: String
    let createdAt: Date

    enum CodingKeys: String, CodingKey {
        case id
        case postId = "post_id"
        case userId = "user_id"
        case parentId = "parent_id"
        case content
        case createdAt = "created_at"
    }
}

struct PostTag: Codable {
    let postId: Int64
    let tagId: Int64

    enum CodingKeys: String, CodingKey {
        case postId = "post_id"
        case tagId = "tag_id"
    }
}

struct User: Codable {
    let id: Int64
    let email: String
    let name: String?
    let age: Int?
    let isActive: Bool
    let metadata: String?
    let address: Any?
    let createdAt: Date
    let tags: Any?
    let avatar: Data?
    let balance: Decimal?
    let externalId: UUID?

    enum CodingKeys: String, CodingKey {
        case id
        case email
        case name
        case age
        case isActive = "is_active"
        case metadata
        case address
        case createdAt = "created_at"
        case tags
        case avatar
        case balance
        case externalId = "external_id"
    }
}

/// Read-only (from view)
struct ActiveUser: Codable {
    let id: Int64?
    let email: String?
    let name: String?
    let createdAt: Date?

    enum CodingKeys: String, CodingKey {
        case id
        case email
        case name
        case createdAt = "created_at"
    }
}
