// Generated by @sqldoc/templates/sqlc -- DO NOT EDIT
package models

import (
	"database/sql"
	"time"
)

type Adoption struct {
	Id int32
	PetId int32
	OwnerId int32
	AdoptedAt time.Time
	AdoptionFee string
	UpdatedBy sql.NullString
}

type AdoptionsAuditLog struct {
	Id int64
	TableName string
	Operation string
	OldData sql.NullString
	NewData sql.NullString
	ChangedAt time.Time
}

type Category struct {
	Id int32
	Name string
	Description sql.NullString
}

type LegacyInventory struct {
	Id int32
	ItemName sql.NullString
	OldSku sql.NullString
	Quantity sql.NullInt32
}

type Location struct {
	Id int32
	Name string
	Address string
	City string
	Zip sql.NullString
}

type MedicalRecord struct {
	Id int32
	PetId int32
	VisitDate time.Time
	Diagnosis string
	Treatment sql.NullString
	VetName sql.NullString
}

type Owner struct {
	Id int32
	Name string
	Email string
	Phone sql.NullString
	CreatedAt sql.NullTime
}

type Pet struct {
	Id int32
	CategoryId sql.NullInt32
	Name string
	Sku string
	Price string
	InternalNotes sql.NullString
	Status string
	CreatedAt sql.NullTime
}

type Review struct {
	Id int32
	PetId int32
	OwnerId int32
	Rating int32
	Body sql.NullString
	LocationId sql.NullInt32
	CreatedAt sql.NullTime
}

type StaffAuditLog struct {
	Id int64
	TableName string
	Operation string
	OldData sql.NullString
	NewData sql.NullString
	ChangedAt time.Time
}
