import { defineTemplate } from '@sqldoc/ns-codegen'
import { activeTables, type EnrichedColumn, enrichRealm } from '../helpers/enrich.ts'
import { singularize, singularizeLast, toCamelCase, toPascalCase } from '../helpers/naming.ts'
import { pgToEloquentCast, pgToPhp } from '../types/pg-to-php.ts'

export default defineTemplate({
  name: 'PHP Eloquent',
  description: 'Generate Laravel Eloquent model classes with casts, fillable, and relationships from SQL schema',
  language: 'php',

  generate(ctx) {
    const schema = enrichRealm(ctx)
    const files: Array<{ path: string; content: string }> = []

    for (const table of activeTables(schema)) {
      const className = toPascalCase(singularizeLast(table.name))
      const lines: string[] = []

      lines.push('<?php')
      lines.push('// Generated by @sqldoc/templates/php-eloquent -- DO NOT EDIT')
      lines.push('')
      lines.push('namespace App\\Models;')
      lines.push('')
      lines.push('use Illuminate\\Database\\Eloquent\\Model;')

      // Collect relationship imports
      const needsBelongsTo = table.belongsTo.length > 0
      const needsHasMany = table.hasMany.length > 0
      if (needsBelongsTo) lines.push('use Illuminate\\Database\\Eloquent\\Relations\\BelongsTo;')
      if (needsHasMany) lines.push('use Illuminate\\Database\\Eloquent\\Relations\\HasMany;')

      lines.push('')

      // PHPDoc block
      lines.push('/**')
      lines.push(` * ${className}`)
      lines.push(' *')
      for (const col of table.columns) {
        const phpType = pgToPhp(col.pgType, col.nullable, col.category)
        lines.push(` * @property ${phpType} $${col.name}`)
      }
      lines.push(' */')

      lines.push(`class ${className} extends Model`)
      lines.push('{')

      // Table name
      lines.push(`    protected $table = '${table.sqlName ?? table.name}';`)
      lines.push('')

      // Primary key (if not standard 'id')
      const pk = table.primaryKey
      if (pk.length === 1 && pk[0] !== 'id') {
        lines.push(`    protected $primaryKey = '${pk[0]}';`)
        lines.push('')
      }

      // Timestamps (disable if no created_at/updated_at)
      const hasCreatedAt = table.columns.some((c) => c.name === 'created_at')
      const hasUpdatedAt = table.columns.some((c) => c.name === 'updated_at')
      if (!hasCreatedAt || !hasUpdatedAt) {
        lines.push('    public $timestamps = false;')
        lines.push('')
      }

      // Fillable (all non-PK, non-serial columns)
      const fillable = table.columns.filter((c) => !c.isPrimaryKey && !c.isSerial)
      if (fillable.length > 0) {
        lines.push('    protected $fillable = [')
        for (const col of fillable) {
          lines.push(`        '${col.name}',`)
        }
        lines.push('    ];')
        lines.push('')
      }

      // Casts
      const casts = buildCasts(table.columns)
      if (casts.length > 0) {
        lines.push('    protected $casts = [')
        for (const [colName, castType] of casts) {
          lines.push(`        '${colName}' => '${castType}',`)
        }
        lines.push('    ];')
        lines.push('')
      }

      // Relationships: belongsTo
      for (const rel of table.belongsTo) {
        const relClassName = toPascalCase(singularizeLast(rel.foreignTable))
        const methodName = toCamelCase(singularize(rel.foreignTable))
        const foreignKey = rel.column
        const expectedFk = `${singularize(rel.foreignTable)}_id`

        lines.push(`    public function ${methodName}(): BelongsTo`)
        lines.push('    {')
        if (foreignKey === expectedFk) {
          lines.push(`        return $this->belongsTo(${relClassName}::class);`)
        } else {
          lines.push(`        return $this->belongsTo(${relClassName}::class, '${foreignKey}');`)
        }
        lines.push('    }')
        lines.push('')
      }

      // Relationships: hasMany
      for (const rel of table.hasMany) {
        const relClassName = toPascalCase(singularizeLast(rel.foreignTable))
        const methodName = toCamelCase(rel.foreignTable)
        const foreignKey = rel.foreignColumn
        const expectedFk = `${singularize(table.name)}_id`

        lines.push(`    public function ${methodName}(): HasMany`)
        lines.push('    {')
        if (foreignKey === expectedFk) {
          lines.push(`        return $this->hasMany(${relClassName}::class);`)
        } else {
          lines.push(`        return $this->hasMany(${relClassName}::class, '${foreignKey}');`)
        }
        lines.push('    }')
        lines.push('')
      }

      lines.push('}')
      lines.push('')

      files.push({ path: `${className}.php`, content: lines.join('\n') })
    }

    // Views (read-only models)
    for (const view of schema.views.filter((v) => !v.skipped)) {
      const className = toPascalCase(singularizeLast(view.name))
      const lines: string[] = []

      lines.push('<?php')
      lines.push('// Generated by @sqldoc/templates/php-eloquent -- DO NOT EDIT')
      lines.push('')
      lines.push('namespace App\\Models;')
      lines.push('')
      lines.push('use Illuminate\\Database\\Eloquent\\Model;')
      lines.push('')
      lines.push('/**')
      lines.push(` * ${className} (read-only view)`)
      lines.push(' *')
      for (const col of view.columns) {
        const phpType = pgToPhp(col.pgType, col.nullable, col.category)
        lines.push(` * @property ${phpType} $${col.name}`)
      }
      lines.push(' */')
      lines.push(`class ${className} extends Model`)
      lines.push('{')
      lines.push(`    protected $table = '${view.name}';`)
      lines.push('    public $timestamps = false;')
      lines.push('}')
      lines.push('')

      files.push({ path: `${className}.php`, content: lines.join('\n') })
    }

    return { files }
  },
})

function buildCasts(columns: EnrichedColumn[]): Array<[string, string]> {
  const casts: Array<[string, string]> = []

  for (const col of columns) {
    // Skip id and standard timestamp columns (Eloquent handles these)
    if (col.name === 'id' || col.name === 'created_at' || col.name === 'updated_at') continue

    const cast = pgToEloquentCast(col.pgType, col.category)
    if (cast && cast !== 'string') {
      casts.push([col.name, cast])
    }
  }

  return casts
}
