import * as fs from 'node:fs'
import * as os from 'node:os'
import * as path from 'node:path'
import { afterEach, beforeEach, describe, expect, it, mockMethod } from '@sqldoc/test-utils'

describe('codegenCommand', () => {
  let tmpDir: string

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'sqldoc-cli-codegen-'))
  })

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true })
  })

  it('does not write SQL to stdout', { timeout: 30_000 }, async () => {
    const nsFile = path.join(tmpDir, 'ns-test.ts')
    fs.writeFileSync(
      nsFile,
      `
      export default {
        name: 'test',
        tags: {
          marker: { description: 'test marker', targets: ['table'] },
        },
        apiVersion: 1,
        generateSQL(ctx) {
          return [{ sql: '-- generated by test namespace' }]
        },
      }
    `,
      'utf-8',
    )

    const sqlFile = path.join(tmpDir, 'schema.sql')
    fs.writeFileSync(
      sqlFile,
      `-- @import './ns-test.ts'
-- @test.marker
CREATE TABLE users (
  id bigserial PRIMARY KEY
);
`,
      'utf-8',
    )

    const writeSpy = mockMethod(process.stdout, 'write', () => true)
    const consoleErrorSpy = mockMethod(console, 'error', () => {})

    const { codegenCommand } = await import('../commands/codegen.ts')
    await codegenCommand(sqlFile, {})

    // codegen should NOT write SQL to stdout (no -o option exists)
    const stdoutOutput = writeSpy.calls.map((c) => String(c[0])).join('')
    expect(stdoutOutput).not.toContain('CREATE TABLE users')

    consoleErrorSpy.restore()
    writeSpy.restore()
  })

  it('throws CliError when errors are encountered', async () => {
    const nsFile = path.join(tmpDir, 'ns-error.ts')
    fs.writeFileSync(
      nsFile,
      `
      export default {
        name: 'broken',
        tags: {
          fail: { description: 'always fails', targets: ['table'] },
        },
        apiVersion: 1,
        generateSQL(ctx) {
          throw new Error('Generator exploded')
        },
      }
    `,
      'utf-8',
    )

    const sqlFile = path.join(tmpDir, 'broken.sql')
    fs.writeFileSync(
      sqlFile,
      `-- @import './ns-error.ts'
-- @broken.fail
CREATE TABLE bad (
  id bigserial PRIMARY KEY
);
`,
      'utf-8',
    )

    const consoleErrorSpy = mockMethod(console, 'error', () => {})
    const writeSpy = mockMethod(process.stdout, 'write', () => true)

    const { codegenCommand } = await import('../commands/codegen.ts')
    const { CliError } = await import('../errors.ts')
    await expect(codegenCommand(sqlFile, {})).rejects.toThrow(CliError)

    consoleErrorSpy.restore()
    writeSpy.restore()
  })
})
