<?php
// Generated by @sqldoc/templates/php-eloquent -- DO NOT EDIT

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * ActiveUser (read-only view)
 *
 * @property ?int $id
 * @property ?string $email
 * @property ?string $name
 * @property ?string $created_at
 */
class ActiveUser extends Model
{
    protected $table = 'active_users';
    public $timestamps = false;
}
