<?php
// Generated by @sqldoc/templates/php-eloquent -- DO NOT EDIT

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * PostTag
 *
 * @property int $post_id
 * @property int $tag_id
 */
class PostTag extends Model
{
    protected $table = 'post_tags';

    public $timestamps = false;

    protected $casts = [
        'post_id' => 'integer',
        'tag_id' => 'integer',
    ];

    public function post(): BelongsTo
    {
        return $this->belongsTo(Post::class);
    }

    public function comment(): BelongsTo
    {
        return $this->belongsTo(Comment::class, 'tag_id');
    }

}
