<?php
// Generated by @sqldoc/templates/php-eloquent -- DO NOT EDIT

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * Post
 *
 * @property int $id
 * @property int $user_id
 * @property string $title
 * @property string $body
 * @property ?string $published_at
 * @property int $view_count
 * @property ?float $rating
 */
class Post extends Model
{
    protected $table = 'content.posts';

    public $timestamps = false;

    protected $fillable = [
        'user_id',
        'title',
        'body',
        'published_at',
        'view_count',
        'rating',
    ];

    protected $casts = [
        'user_id' => 'integer',
        'published_at' => 'datetime',
        'view_count' => 'integer',
        'rating' => 'float',
    ];

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function comments(): HasMany
    {
        return $this->hasMany(Comment::class);
    }

    public function postTags(): HasMany
    {
        return $this->hasMany(PostTag::class);
    }

}
