<?php
// Generated by @sqldoc/templates/php-eloquent -- DO NOT EDIT

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * User
 *
 * @property int $id
 * @property string $email
 * @property ?string $name
 * @property ?int $age
 * @property bool $is_active
 * @property ?array $metadata
 * @property mixed $address
 * @property string $created_at
 * @property mixed $tags
 * @property ?string $avatar
 * @property ?float $balance
 * @property ?string $external_id
 */
class User extends Model
{
    protected $table = 'users';

    public $timestamps = false;

    protected $fillable = [
        'email',
        'name',
        'age',
        'is_active',
        'metadata',
        'address',
        'created_at',
        'tags',
        'avatar',
        'balance',
        'external_id',
    ];

    protected $casts = [
        'age' => 'integer',
        'is_active' => 'boolean',
        'metadata' => 'array',
        'balance' => 'decimal',
    ];

    public function posts(): HasMany
    {
        return $this->hasMany(Post::class);
    }

    public function comments(): HasMany
    {
        return $this->hasMany(Comment::class);
    }

}
