import { describe, it } from 'node:test'
import { expect } from '@sqldoc/test-utils'
import { renderHtml } from '../../renderers/html.ts'
import { makeMinimalSchema, makeTestSchema } from './fixture.ts'

describe('renderHtml', () => {
  const schema = makeTestSchema()

  it('output starts with <!DOCTYPE html>', () => {
    const result = renderHtml(schema)
    expect(result.trimStart()).toMatch(/^<!DOCTYPE html>/)
  })

  it('output contains <title> with schema title', () => {
    const result = renderHtml(schema)
    expect(result).toContain('<title>Test Schema Docs</title>')
  })

  it('output contains sidebar nav with table links', () => {
    const result = renderHtml(schema)
    expect(result).toContain('class="sidebar"')
    expect(result).toContain('<a href="#users">users</a>')
    expect(result).toContain('<a href="#posts">posts</a>')
  })

  it('output contains sidebar Views section with view links', () => {
    const result = renderHtml(schema)
    expect(result).toContain('<h2>Views</h2>')
    expect(result).toContain('<a href="#active_users">active_users</a>')
  })

  it('output contains <pre class="mermaid"> with ERD content', () => {
    const result = renderHtml(schema)
    expect(result).toContain('<pre class="mermaid">')
    expect(result).toContain('erDiagram')
  })

  it('output contains <section id="{tableName}"> for each table', () => {
    const result = renderHtml(schema)
    expect(result).toContain('<section id="users">')
    expect(result).toContain('<section id="posts">')
    expect(result).toContain('<section id="active_users">')
  })

  it('generated tables have generated-badge span', () => {
    const result = renderHtml(schema)
    expect(result).toContain('class="generated-badge"')
    expect(result).toContain('Generated by @audit')
  })

  it('columns rendered in HTML table', () => {
    const result = renderHtml(schema)
    expect(result).toContain('<th>Column</th>')
    expect(result).toContain('<th>Type</th>')
    expect(result).toContain('<td>bigserial</td>')
  })

  it('annotations rendered as <span class="annotation">', () => {
    const result = renderHtml(schema)
    expect(result).toContain('<span class="annotation">')
    expect(result).toContain('Audited (insert, update)')
    expect(result).toContain('RLS enabled')
  })

  it('HTML-escaped content (no raw < or > in user strings)', () => {
    // Create schema with potentially dangerous content
    const dangerousSchema = makeTestSchema()
    dangerousSchema.tables[0].description = '<script>alert("xss")</script>'
    dangerousSchema.title = 'Test <b>bold</b> title'

    const result = renderHtml(dangerousSchema)
    expect(result).not.toContain('<script>alert')
    expect(result).toContain('&lt;script&gt;')
    expect(result).toContain('&lt;b&gt;bold&lt;/b&gt;')
  })

  it('script tag contains IntersectionObserver', () => {
    const result = renderHtml(schema)
    expect(result).toContain('<script type="module">')
    expect(result).toContain('IntersectionObserver')
  })

  it('embedded CSS contains sidebar and content styles', () => {
    const result = renderHtml(schema)
    expect(result).toContain('<style>')
    expect(result).toContain('.sidebar')
    expect(result).toContain('.content')
    expect(result).toContain('.annotation')
    expect(result).toContain('.generated-badge')
  })

  it('no Views sidebar section when no views present', () => {
    const minimal = makeMinimalSchema()
    const result = renderHtml(minimal)
    // Should not have the Views heading in sidebar
    // The sidebar should not contain Views h2 since no views
    const sidebarMatch = result.match(/<nav class="sidebar">([\s\S]*?)<\/nav>/)
    expect(sidebarMatch).toBeTruthy()
    expect(sidebarMatch![1]).not.toContain('<h2>Views</h2>')
  })

  it('table with previously shows "formerly" paragraph', () => {
    const result = renderHtml(schema)
    expect(result).toContain('class="previously"')
    expect(result).toContain('formerly: old_users')
  })

  it('column with previously shows "formerly" in description cell', () => {
    const result = renderHtml(schema)
    expect(result).toContain('formerly: email_address')
  })

  it('description paragraph has class "description"', () => {
    const result = renderHtml(schema)
    expect(result).toContain('class="description"')
  })

  it('timestamp paragraph has class "timestamp"', () => {
    const result = renderHtml(schema)
    expect(result).toContain('class="timestamp"')
    expect(result).toContain('Generated:')
  })
})
