import { describe, expect, it } from 'vitest'
import { renderMarkdown } from '../../renderers/markdown'
import { makeMinimalSchema, makeTestSchema } from './fixture'

describe('renderMarkdown', () => {
  // Reuse the shared fixture for most tests
  const schema = makeTestSchema()

  // Generate once for all tests
  const _output = renderMarkdown(schema)

  it('output contains title as H1', () => {
    const result = renderMarkdown(schema)
    expect(result).toContain('# Test Schema Docs')
  })

  it('output contains mermaid code block with erDiagram content', () => {
    const result = renderMarkdown(schema)
    expect(result).toContain('```mermaid')
    expect(result).toContain('erDiagram')
    expect(result).toContain('bigserial id PK')
    expect(result).toContain('```')
  })

  it('output contains table of contents with anchor links', () => {
    const result = renderMarkdown(schema)
    expect(result).toContain('## Contents')
    expect(result).toMatch(/\[users\]\(#users\)/)
    expect(result).toMatch(/\[posts\]\(#posts\)/)
    expect(result).toMatch(/\[active_users\]\(#active_users\)/)
  })

  it('each table has columns table with correct headers', () => {
    const result = renderMarkdown(schema)
    expect(result).toContain('| Column | Type | Nullable | PK | FK | Description |')
  })

  it('generated tables have "(Generated by @namespace)" annotation', () => {
    const result = renderMarkdown(schema)
    expect(result).toContain('(Generated by @audit)')
  })

  it('non-generated tables do not have generated annotation', () => {
    const result = renderMarkdown(schema)
    // "users" section should NOT have "Generated by"
    const usersIdx = result.indexOf('### users')
    const postsIdx = result.indexOf('### posts')
    const between = result.slice(usersIdx, postsIdx)
    expect(between).not.toContain('Generated by')
  })

  it('table with previously shows "formerly" line', () => {
    const result = renderMarkdown(schema)
    expect(result).toContain('*formerly: old_users*')
  })

  it('column with previously shows "formerly" in description cell', () => {
    const result = renderMarkdown(schema)
    expect(result).toContain('*formerly: email_address*')
  })

  it('annotations rendered as blockquotes', () => {
    const result = renderMarkdown(schema)
    expect(result).toContain('> Audited (insert, update)')
    expect(result).toContain('> RLS enabled')
  })

  it('extra column headers appear in column table', () => {
    const result = renderMarkdown(schema)
    expect(result).toContain('Anonymization')
    expect(result).toContain('Masked: anon.fake_email()')
  })

  it('FK section rendered when foreignKeys present', () => {
    const result = renderMarkdown(schema)
    expect(result).toContain('#### Foreign Keys')
    expect(result).toContain('posts_user_id_fkey')
    expect(result).toContain('users(id)')
  })

  it('indexes section rendered when indexes present', () => {
    const result = renderMarkdown(schema)
    expect(result).toContain('#### Indexes')
    expect(result).toContain('users_email_idx')
    expect(result).toContain('UNIQUE')
  })

  it('views section rendered when views present', () => {
    const result = renderMarkdown(schema)
    expect(result).toContain('## Views')
    expect(result).toContain('### active_users')
  })

  it('empty schema produces minimal output (title + empty sections)', () => {
    const minimal = makeMinimalSchema()
    const result = renderMarkdown(minimal)
    expect(result).toContain('# Empty Schema')
    expect(result).toContain('```mermaid')
    expect(result).not.toContain('## Views')
  })

  it('column rows contain correct PK/FK markers', () => {
    const result = renderMarkdown(schema)
    // The "id" column in users should have PK=Y
    // We need to find the users columns table and check the id row
    const lines = result.split('\n')
    const idLine = lines.find((l) => l.includes('| id |') && l.includes('bigserial'))
    expect(idLine).toBeDefined()
    expect(idLine).toContain('| Y |')

    // user_id in posts should have FK=Y
    const fkLine = lines.find((l) => l.includes('| user_id |'))
    expect(fkLine).toBeDefined()
    expect(fkLine).toMatch(/\|\s*Y\s*\|/)
  })

  it('generated timestamp is present', () => {
    const result = renderMarkdown(schema)
    expect(result).toContain('*Generated:')
  })
})
