import fs from 'node:fs'
import path from 'node:path'

export interface HomepageExample {
  input: string
  output: string
}

declare const data: HomepageExample
export { data }

export default {
  load(): HomepageExample {
    const dir = path.resolve(import.meta.dirname!, '../examples')
    const input = fs.readFileSync(path.join(dir, 'homepage.sql'), 'utf-8').trim()
    const compiled = fs.readFileSync(path.join(dir, 'homepage-compiled.sql'), 'utf-8').trim()

    // The compiled output includes the original SQL followed by generated SQL.
    // Extract only the generated portion (after the original CREATE TABLE block).
    const genMarker = '-- Generated by sqldoc'
    const genIdx = compiled.indexOf(genMarker)
    const output = genIdx !== -1 ? compiled.slice(genIdx).trim() : compiled

    return { input, output }
  },
}
