// Generated by @sqldoc/templates/kysely -- DO NOT EDIT

import type { Generated } from 'kysely'

export interface Adoption {
  id: number
  pet_id: number
  owner_id: number
  adopted_at: Generated<Date>
  adoption_fee: Generated<string>
  updated_by: string | null
}

export interface AdoptionsAuditLog {
  id: number
  table_name: string
  operation: string
  old_data: string | null
  new_data: string | null
  changed_at: Generated<Date>
}

export interface Category {
  id: number
  name: string
  description: string | null
}

export interface LegacyInventory {
  id: number
  item_name: string | null
  old_sku: string | null
  quantity: Generated<number | null>
}

export interface Location {
  id: number
  name: string
  address: string
  city: string
  zip: string | null
}

export interface MedicalRecord {
  id: number
  pet_id: number
  visit_date: Generated<string>
  diagnosis: string
  treatment: string | null
  vet_name: string | null
}

export interface Owner {
  id: number
  name: string
  email: string
  phone: string | null
  created_at: Generated<Date | null>
}

export interface Pet {
  id: number
  category_id: number | null
  name: string
  sku: string
  price: Generated<string>
  internal_notes: string | null
  status: Generated<string>
  created_at: Generated<Date | null>
}

export interface Review {
  id: number
  pet_id: number
  owner_id: number
  rating: number
  body: string | null
  location_id: number | null
  created_at: Generated<Date | null>
}

export interface StaffAuditLog {
  id: number
  table_name: string
  operation: string
  old_data: string | null
  new_data: string | null
  changed_at: Generated<Date>
}

export interface Database {
  'adoptions': Adoption
  'adoptions_audit_log': AdoptionsAuditLog
  'categories': Category
  'legacy_inventory': LegacyInventory
  'locations': Location
  'medical_records': MedicalRecord
  'owners': Owner
  'pets': Pet
  'reviews': Review
  'staff_audit_log': StaffAuditLog
}
